README.md, specs/Stack.spec.js, src/ColorUtils.js, src/components/charts/stack/Stack.js, src/components/charts/stack/StackDots.js, src/components/charts/stack/StackSlicer.js, src/components/charts/stack/index.js, test/ColorUtils.test.js
see https://github.com/plouc/nivo/issues/10
=> Add ability to filter stack component layers

src/components/axes/Axes.js, src/components/axes/Axis.js, src/lib/axes.js, test/lib/axes.test.js
fix https://github.com/plouc/nivo/issues/57
=> feat(axis): add support for custom tick values/count

src/components/charts/pie/Pie.js, src/components/charts/pie/props.js
see https://github.com/plouc/nivo/issues/68
=> feat(pie): add ability to use default dataset order

src/components/charts/line/Line.js, src/components/charts/line/LineDots.js, src/components/charts/line/LineSlices.js, src/components/charts/line/LineSlicesItem.js, src/components/charts/line/props.js, stories/charts/line.stories.js
Hide part of the Line with missing data #61
=> feat(line): part of a line with missing data was hidden

packages/nivo-legends/src/svg/BoxLegendSvg.js, packages/nivo-legends/src/svg/LegendSvg.js, packages/nivo-legends/src/svg/LegendSvgItem.js
=> Added fill variable instead of hardcoded black

packages/nivo-legends/src/canvas/index.js, packages/nivo-legends/src/props.js, packages/nivo-legends/src/svg/BoxLegendSvg.js, packages/nivo-legends/src/svg/LegendSvg.js, packages/nivo-legends/src/svg/LegendSvgItem.js, packages/nivo-legends/tests/svg/LegendSvgItem.test.js
See https://github.com/plouc/nivo/issues/112.
This MR is based upon https://github.com/plouc/nivo/pull/113 by @knackjax.
=> feat(legends): add ability to configure text color

CONTRIBUTING.md
Hey @plouc,
just coming back to your library, because I need some additions. While wanting to start, I stumbled over the lack of a getting start guide / explanations. This is an attempt to document the bare basics to get started.
=> docs(CONTRIBUTING): explain development setup

packages/nivo-line/src/LineAreas.js
Fixing stacked area graphs as discussed in issue #150
=> Make line areas stack in front of each other visibly.

website/src/components/charts/stream/Stream.js
Fix https://github.com/plouc/nivo/issues/178
=> fix(website): fix website Stream example code

packages/nivo-heatmap/index.d.ts
Added typescript type definitions for the heat map package. The declarations are in index.d.ts
=> Type declaration module for Heatmap package

packages/nivo-pie/index.d.ts, packages/nivo-pie/src/Pie.js, packages/nivo-pie/src/PieSlice.js, packages/nivo-pie/src/props.js, website/src/components/charts/pie/Pie.js, website/src/components/charts/pie/props.js, website/src/components/charts/pie/propsMapper.js
see https://github.com/plouc/nivo/issues/192
=> feat(pie): add support for custom tooltip

packages/nivo-radar/src/Radar.js, website/src/components/charts/radar/Radar.js, website/src/components/charts/radar/props.js
see https://github.com/plouc/nivo/issues/124
=> feat(radar): add ability to define max value

packages/nivo-bar/src/BarItem.js, packages/nivo-line/src/LineSlices.js
see https://github.com/plouc/nivo/issues/177
=> fix(line): fix LineSlices id prop type

.storybook/config.js, Makefile, packages/nivo-calendar/index.d.ts, packages/nivo-calendar/package.json, packages/nivo-calendar/src/Calendar.js, packages/nivo-calendar/src/CalendarDay.js, packages/nivo-calendar/src/computeCalendar.js, packages/nivo-calendar/src/props.js, packages/nivo-calendar/stories/.eslintrc.yml, packages/nivo-calendar/stories/calendar.stories.js, website/src/components/charts/calendar/Calendar.js, website/src/components/charts/calendar/props.js, website/src/components/charts/calendar/propsMapper.js
- https://github.com/plouc/nivo/issues/197
- https://github.com/plouc/nivo/issues/217
- https://github.com/plouc/nivo/issues/213
=> Improve @nivo/calendar package

packages/nivo-calendar/src/enhance.js
=> Fix calendar crashing when no data is available

packages/nivo-scatterplot/src/props.js
https://github.com/plouc/nivo/issues/243
=> feat(scatterplot): remove unused min/max x/y

packages/scatterplot/src/ScatterPlot.js, packages/scatterplot/src/props.js
As the title said, simply added markers to scatterplot SVG
=> feat(scatterplot-markers): add markers to scatterplot SVG

packages/chord/src/Chord.js, packages/chord/src/ChordCanvas.js
see https://github.com/plouc/nivo/issues/304
=> fix(chord): skip rendering for zero/negative radius

packages/axes/src/canvas.js, packages/bar/tests/__snapshots__/Bar.test.js.snap, packages/circle-packing/src/BubbleCanvas.js, packages/core/src/components/cartesian/markers/CartesianMarkers.js, packages/core/src/hocs/withTheme.js, packages/core/src/theming/defaultTheme.js, packages/core/src/theming/extend.js, packages/core/src/theming/index.js, packages/core/src/theming/propTypes.js, packages/heatmap/src/canvas.js, packages/heatmap/tests/__snapshots__/HeatMap.test.js.snap, packages/legends/tests/svg/__snapshots__/LegendSvgItem.test.js.snap, packages/line/tests/__snapshots__/Line.test.js.snap, packages/pie/src/canvas.js, packages/scatterplot/tests/__snapshots__/ScatterPlot.test.js.snap, packages/treemap/src/TreeMapCanvas.js, website/src/nivoTheme.js
This PR will allow to use global theme settings for fonts, using `fontFamily`, `fontSize` and `textColor`
=> feat(theming): improve theming

packages/sunburst/src/Sunburst.js, packages/sunburst/stories/sunburst.stories.js
=> Allow non-inherited Sunburst child colors

packages/axes/package.json, packages/bar/package.json, packages/bullet/package.json, packages/calendar/package.json, packages/chord/package.json, packages/circle-packing/package.json, packages/core/package.json, packages/heatmap/package.json, packages/legends/package.json, packages/line/package.json, packages/parallel-coordinates/package.json, packages/pie/package.json, packages/radar/package.json, packages/sankey/package.json, packages/scatterplot/package.json, packages/stream/package.json, packages/sunburst/package.json, packages/treemap/package.json, packages/voronoi/package.json, packages/waffle/package.json, yarn.lock
Fix https://github.com/plouc/nivo/issues/389
=> chore(deps): upgrade few dependencies

conf/rollup.config.js, packages/bar/src/Bar.js, packages/bar/src/BarCanvas.js, packages/bar/src/compute/index.js, packages/bar/src/compute/legends.js, packages/bar/tests/Bar.test.js
- fix https://github.com/plouc/nivo/issues/478
- fix https://github.com/plouc/nivo/issues/464
=> Various improvements and fixes on @nivo/bar package

packages/sankey/src/enhance.js
Fixes issue/bug referenced in comments of #496
=> Fix custom sankey node sorting

packages/scales/src/timeScale.js
fix https://github.com/plouc/nivo/issues/537
=> fix(scales): fix time scale instantiation

packages/geo/src/Choropleth.js, packages/geo/src/ChoroplethCanvas.js, packages/geo/src/hooks.js, packages/geo/src/props.js, website/src/data/components/choropleth/props.js, website/src/pages/choropleth/canvas.js, website/src/pages/choropleth/index.js
Added domain prop to the choropleths so the color grading can be controlled from the top level.
Went ahead made it a required prop. Let me know if it would be preferable to make it optional.
=> Added domain prop to Choropleth and Choropleth Canvas

packages/radar/src/RadarTooltipItem.js
fix https://github.com/plouc/nivo/issues/542
=> fix(radar): fix Radar cached tooltip

packages/sankey/stories/sankey.stories.js
=> fix(sankey): change custom align story to use correct align property

packages/stream/index.d.ts
- missing type of MotionProps
- wrong key of prop offsetType
=> [stream] Fix bugs in index.d.ts

packages/axes/index.d.ts, packages/legends/index.d.ts, packages/line/index.d.ts
Add missing types to match example
https://nivo.rocks/line/
=> Add missing types to LineSvgProps,  AxisProps and LegendProps (Line/ResponsiveLine)

packages/radar/src/RadarTooltipItem.js, packages/radar/stories/radar.stories.js
I needed functionality to format tooltips regards key in radar chart.
=> feat(radar): Tooltip format function gets key

packages/bar/index.d.ts
fix https://github.com/plouc/nivo/issues/604
fix https://github.com/plouc/nivo/issues/565
=> fix(bar): fix types

packages/axes/src/components/Axis.js, packages/bar/stories/bar.stories.js
Fix https://github.com/plouc/nivo/issues/579
=> fix(axes): treat renderTick as a React component

packages/scales/index.d.ts, packages/scales/src/linearScale.js, packages/scales/tests/linearScale.test.js, website/src/data/components/line/defaults.js, website/src/pages/swarmplot/canvas.js, website/src/pages/swarmplot/index.js
fix https://github.com/plouc/nivo/issues/638
=> feat(scales): add ability to reverse linear scale

Makefile, packages/voronoi/package.json, packages/voronoi/tests/.eslintrc.yml, packages/voronoi/tests/computeMesh.test.js, yarn.lock
fix https://github.com/plouc/nivo/issues/545
=> fix(voronoi): upgrade d3-delaunay to fix single/collinearpoints

packages/line/index.d.ts
- fix https://github.com/plouc/nivo/issues/615
=> feat(line): update TypeScript definitions

website/src/components/components/ComponentTabs.js
This pull request fixes a responsive problem at the component's tabs, as asked at issue #684 . 
Closes #684
=> Fixing responsive problems at component's tab

packages/sankey/src/SankeyLinksItem.js
=> Fix issue with gradient links and spaces in IDs

website/src/data/components/line/props.js, website/src/data/components/scatterplot/props.js
fix https://github.com/plouc/nivo/issues/877
=> feat(website): add link to d3-format documentation for line & scatterplot value formatters

packages/line/index.d.ts
Some curve options where missing (basis, cardinal, catmullRom)
=> #197 Updated @nivo/line typescript definition to add all curve options

packages/core/index.d.ts
Will add more as I come across it. Love your solution btw!
=> Added crosshair definitions

packages/line/src/Mesh.js, packages/voronoi/src/Mesh.js
https://github.com/plouc/nivo/issues/756
=> Fix onMouseLeave firing (Line)

website/src/data/components/line/meta.yml
=> fix(website): fix spelling mistake

packages/pie/src/PieLegends.js, packages/pie/src/PieSlice.js, packages/pie/stories/pie.stories.js
- Fix proptype stating label is required for PieSlice
- Fix PieLegend to use label if available, otherwise id
- Add knob to storybook to display legend
Close #794
Close #808
=> fix(pie): address some issues with data label prop

packages/line/src/Line.js
Hi!
The changes pass state variables to a custom layer in the Line component. For example, it allows me to replace crosshair with a custom implementation.
=> feat(line): pass the state to a custom layer

packages/line/src/LineCanvas.js, packages/line/stories/LineCanvas.stories.js
This might already resolve @ojvilau 's problem #978  
but should definitely be looked at by someone who knows their way around this codebase.
=> feat(line): add custom layer support to LineCanvas

packages/radar/index.d.ts
=> fix(radar): add theme prop to types

packages/sunburst/src/Sunburst.js, packages/sunburst/src/SunburstArc.js, packages/sunburst/stories/sunburst.stories.js
=> Sunburst: custom tooltip

website/src/components/components/ComponentSettings.js, website/src/components/controls/ColorPickerControl.js, website/src/components/controls/ControlsGroup.js, website/src/components/controls/LineWidthControl.js, website/src/components/controls/ObjectControl.js, website/src/components/controls/PropertyHeader.js, website/src/data/components/area-bump/props.js, website/src/data/components/bar/props.js, website/src/data/components/bubble/props.js, website/src/data/components/bullet/props.js, website/src/data/components/bump/props.js, website/src/data/components/calendar/props.js, website/src/data/components/chord/props.js, website/src/data/components/choropleth/props.js, website/src/data/components/funnel/props.js, website/src/data/components/geo/props.js, website/src/data/components/heatmap/props.js, website/src/data/components/line/props.js, website/src/data/components/parallel-coordinates/props.js, website/src/data/components/pie/props.js, website/src/data/components/radar/props.js, website/src/data/components/sankey/props.js, website/src/data/components/scatterplot/props.js, website/src/data/components/stream/props.js, website/src/data/components/swarmplot/props.js, website/src/data/components/waffle/props.js, website/src/data/nav.js, website/src/lib/componentProperties.js, website/src/pages/guides/theming.js
- fix https://github.com/plouc/nivo/issues/308
- fix https://github.com/plouc/nivo/issues/1022
=> Add theming guide

packages/scatterplot/src/ScatterPlotCanvas.js
=> fix(scatterplot): fix canvas missing annotations layer

packages/scales/src/index.js, packages/swarmplot/src/compute.js, packages/swarmplot/src/hooks.js, packages/swarmplot/stories/SwarmPlot.stories.js
Fixes #1120 
Changes made in this PR,
=> feat(swarmplot): add time scale support

packages/core/index.d.ts, packages/core/src/components/defs/gradients/LinearGradient.js
=> fix(core): add Defs types and export for typescript

packages/scatterplot/index.d.ts, packages/scatterplot/src/props.js
=> fix(scatterplot): adjust type/proptype of `data[].id` prop

packages/sankey/src/SankeyLinksItem.js
Closes https://github.com/plouc/nivo/issues/1150
=> fix(sankey): Fix issue with gradient and parentheses in IDs

packages/bump/index.d.ts
for Handling Null or undefined type of input in bump graph
=> fix(bump): update input datum types for undefined/null

packages/radar/src/RadarGridLevels.js
I reverted animating between grid shapes since it wasn't present in the previous version but caused issues above. This will still animate when changing the number of levels shown as it did previously.
Close #1178
=> fix(radar): fix issue with points being outside circular grid

website/src/pages/calendar/canvas.js, website/src/pages/calendar/index.js
=> fix(website): fix crash caused by calendar tooltip

packages/annotations/package.json, packages/axes/package.json, packages/bar/package.json, packages/bullet/package.json, packages/bump/package.json, packages/calendar/package.json, packages/chord/package.json, packages/circle-packing/package.json, packages/core/package.json, packages/funnel/package.json, packages/geo/package.json, packages/heatmap/package.json, packages/legends/package.json, packages/line/package.json, packages/network/package.json, packages/parallel-coordinates/package.json, packages/pie/package.json, packages/radar/package.json, packages/sankey/package.json, packages/scatterplot/package.json, packages/stream/package.json, packages/sunburst/package.json, packages/swarmplot/package.json, packages/treemap/package.json, packages/voronoi/package.json, packages/waffle/package.json
Fix https://github.com/plouc/nivo/issues/1256
=> Fix packages react version range

packages/core/index.d.ts
What the title says :) Taking this as an opportunity to thank you for this fantastic lib 👍🏼
=> Fix type definition of PatternSquaresDef

packages/funnel/package.json
=> fix(funnel): fix dependencies on other nivo packages

CONTRIBUTING.md
@wyze @plouc this is a safe & easy little PR that'll mean I'm no longer a first-time contributor, so future PRs (and past ones i.e #1494) won't need to be approved everytime I push a commit for CI to run.
=> chore(docs): fix typo

packages/generators/package.json, packages/generators/src/bullet.ts, packages/generators/src/chord.ts, packages/generators/src/color.js, packages/generators/src/color.ts, packages/generators/src/index.ts, packages/generators/src/network.ts, packages/generators/src/parallelCoordinates.ts, packages/generators/src/sankey.ts, packages/generators/src/sets/countryCodes.ts, packages/generators/src/sets/index.js, packages/generators/src/sets/index.ts, packages/generators/src/sets/names.ts, packages/generators/src/sets/programmingLanguages.ts, packages/generators/src/swarmplot.ts, packages/generators/tsconfig.json, tsconfig.monorepo.json, yarn.lock
=> feat(generators): migrate package to typescript

packages/swarmplot/src/SwarmPlotNode.js, packages/swarmplot/tests/Swarmplot.test.js
ref https://github.com/plouc/nivo/issues/1530
=> fix(swarmplot): fix swarmplot node onMouseMove event

packages/heatmap/src/hooks.js
=> fix(heatmap): return currentCellId from useHeatmap hook

packages/bar/index.d.ts, packages/bar/src/Bar.js, packages/bar/src/BarCanvas.js, packages/bar/src/props.js, packages/pie/src/Pie.tsx, packages/pie/src/PieCanvas.tsx, packages/pie/src/types.ts
=> fix(pie/bar): pass renderWrapper prop to container

packages/treemap/index.d.ts
=> fix(treemap): adjust label type to accept a function

packages/legends/src/types.ts
See https://github.com/plouc/nivo/pull/1512#pullrequestreview-668979398
=> fix(legends): mark data and padding props as optional

packages/line/index.d.ts
=> fix(line): update types from DataFormatter to ValueFormat

packages/core/index.d.ts
=> fix(core): export ThemeProvider in typings

packages/geo/index.d.ts
=> fix(geo): add legends prop to typings for Choropleth

packages/line/index.d.ts
=> fix(line): correct typing for lineGenerator prop

packages/bar/index.d.ts
=> fix(bar): add getTooltipLabel to BarItemProps typings

packages/core/index.d.ts, packages/core/src/theming/defaultTheme.js, packages/core/src/theming/propTypes.js, packages/legends/src/svg/BoxLegendSvg.tsx, packages/legends/src/svg/LegendSvg.tsx, packages/legends/src/svg/LegendSvgItem.tsx, packages/legends/src/svg/symbols/SymbolCircle.tsx, packages/legends/src/svg/symbols/SymbolDiamond.tsx, packages/legends/src/svg/symbols/SymbolSquare.tsx, packages/legends/src/svg/symbols/SymbolTriangle.tsx, packages/legends/src/svg/symbols/types.ts, packages/legends/src/types.ts, packages/legends/tests/svg/__snapshots__/LegendSvgItem.test.tsx.snap, packages/line/src/Line.js, packages/line/src/hooks.js
=> feat(line): add ability to toggle serie via legend item

packages/bump/src/bump/Bump.js
Here is an example of a StickyLine by clicking a line. Make sure to go over to the Bump chart on the left nav menu.
https://codesandbox.io/s/nivo-forked-tm26x?file=/src/charts/Bump.tsx
=> feat(bump): add additional props to custom layers

packages/pie/src/PieLegends.tsx, packages/pie/tests/Pie.test.tsx
=> fix(pie): use legend.data property if supplied

packages/stream/index.d.ts, packages/stream/src/Stream.js, packages/stream/src/hooks.js, packages/stream/src/props.js, packages/stream/stories/stream.stories.js, website/src/data/components/stream/meta.yml, website/src/data/components/stream/props.js
=> feat(stream): add ability to customize legend label

packages/network/index.d.ts, packages/network/src/AnimatedNodes.js, packages/network/src/Network.js, packages/network/src/NetworkCanvas.js, packages/network/src/Node.js, packages/network/src/StaticNodes.js, packages/network/src/props.js, packages/network/stories/networkCanvas.stories.js, website/src/data/components/network/props.js, website/src/pages/network/canvas.js, website/src/pages/network/index.js
Close #1351 
Additionally this brings missing tooltip functionality to the canvas flavor.
=> feat(network): add onClick support for node

packages/axes/src/components/Grid.tsx, packages/axes/src/compute.ts, packages/axes/src/types.ts, packages/line/index.d.ts, yarn.lock
Close #1101
Close #1410
Here is an issue https://github.com/d3/d3-scale/issues/245 describing exactly what we are seeing and a workaround. Currently we are only doing this if we detect that our ticks should be days.
=> fix(axes): fix time scale bug with days crossing a new month

packages/bar/src/BarItem.js, packages/bar/src/BarTooltip.js, packages/bar/src/props.js, packages/bar/stories/bar.stories.js, packages/bar/tests/Bar.test.js
=> fix(bar): fix inconsistency with custom tooltip

packages/scatterplot/index.d.ts, packages/scatterplot/src/ScatterPlot.js, packages/scatterplot/src/compute.js, packages/scatterplot/src/hooks.js, packages/scatterplot/src/props.js, packages/scatterplot/tests/ScatterPlot.test.js, website/src/data/components/scatterplot/props.js
=> feat(scatterplot): add ability to specify nodeId accessor

packages/scales/index.d.ts, packages/scales/src/symlogScale.js, packages/scales/tests/symlogScale.test.js
=> feat(scales): add reverse option to symlog scale

packages/bar/src/BarItem.js, packages/bar/src/compute/grouped.js, packages/bar/src/compute/stacked.js, packages/bar/src/props.js, packages/bar/tests/Bar.test.js
=> fix(bar): fix when values are updated from 0 in grouped mode

packages/sankey/src/hooks.js
=> fix(sankey): use node color for link color

website/src/data/components/bar/mapper.js
Close #1623 
Close #1624 
Supersedes #1625
=> fix(website): update bar tooltip to prevent crash

packages/bullet/src/Bullet.tsx, packages/bullet/src/BulletItem.tsx, packages/bullet/src/compute.ts, packages/bullet/src/hooks.ts, packages/bullet/src/props.ts, packages/bullet/src/types.ts, packages/bullet/stories/bullet.stories.tsx, packages/bullet/tests/Bullet.test.tsx, website/src/data/components/bullet/meta.yml, website/src/data/components/bullet/props.js, website/src/pages/bullet/index.js
=> feat(bullet): support minValue/maxValue properties

packages/chord/index.d.ts
- legends was missing
- ribbonBorderColor was missing the type
refs #821
=> fix(chord): fix missing typescript properties

packages/bump/index.d.ts, packages/chord/index.d.ts, packages/radar/index.d.ts
=> fix(packages): provide datum to InheritedColorConfig type

website/src/pages/treemap/index.js
=> fix(website): show treemap data correctly

packages/line/src/Lines.js
=> fix(line): make copy of lines data before reversing

packages/axes/src/components/Axes.tsx, packages/bar/src/types.ts, packages/bump/index.d.ts, packages/marimekko/src/types.ts
=> fix(axes): support null props to Axes component

packages/annotations/package.json, packages/arcs/package.json, packages/axes/package.json, packages/bar/package.json, packages/bullet/package.json, packages/bump/package.json, packages/circle-packing/package.json, packages/core/package.json, packages/funnel/package.json, packages/heatmap/package.json, packages/line/package.json, packages/marimekko/package.json, packages/parallel-coordinates/package.json, packages/radar/package.json, packages/sankey/package.json, packages/stream/package.json, packages/swarmplot/package.json, packages/tooltip/package.json, packages/treemap/package.json, yarn.lock
=> chore(deps): upgrade react-spring to v9.2.4

packages/bullet/src/Bullet.tsx, packages/bullet/src/BulletItem.tsx, packages/bullet/src/BulletTooltip.tsx, packages/bullet/src/props.ts, packages/bullet/src/types.ts, packages/bullet/stories/bullet.stories.tsx, packages/bullet/tests/Bullet.test.tsx
=> feat(bullet): add custom tooltip

packages/axes/src/canvas.ts
This is a fix for:
https://github.com/plouc/nivo/issues/1704
=> Allow fontWeight set in theme to effect canvas axes

README.md
=> Add link to header image

packages/radar/src/Radar.tsx, packages/radar/src/hooks.ts, packages/radar/src/types.ts, packages/radar/stories/radar.stories.tsx, packages/radar/tests/Radar.test.tsx
Improve Radar component's legend data to be customizable.
[Related issues](https://github.com/plouc/nivo/issues/1785)
=> fix(radar): improve radar's legend data to be customizable

packages/core/index.d.ts
Export missing linearGradientDef function type.
=> fix(core): export linearGradientDef in typings

packages/core/index.d.ts
=> chore(core): export `useMeasure` in typings

packages/pie/src/Arcs.tsx
=> fix(pie) custom tooltip not updated

website/src/data/components/line/defaults.ts
I ran into the same problem as this [issue](https://github.com/plouc/nivo/issues/1771) and fixed it.
=> fix(website): remove orient prop from axisBottom and axisLeft

packages/annotations/src/compute.ts, packages/bar/src/compute/legends.ts, packages/boxplot/src/compute/legends.ts, packages/calendar/src/compute/calendar.ts, packages/calendar/src/compute/timeRange.ts, packages/colors/src/inheritedColor.ts, packages/colors/src/scales/ordinalColorScale.ts, packages/core/src/motion/context.js, packages/express/src/index.ts, packages/express/src/validation.ts, packages/geo/src/hooks.js, packages/marimekko/src/hooks.ts, packages/sankey/src/Sankey.tsx, packages/sankey/src/hooks.ts, packages/static/src/renderer.ts
Close: #2347 
Local module comparison with `@nivo/core` linked:
=> fix: Lodash - use module imports

tsconfig.monorepo.json
=> Resolved BoxPlot types not being included in build output

packages/bar/src/ResponsiveBar.tsx, packages/bar/src/ResponsiveBarCanvas.tsx
People can use them if it's not just an inline Omit type.
=> feat/export responsive bar props TypeScript types

packages/bar/src/Bar.tsx
Resolves #1778, #2297
Was using a custom package with this change for over a year with no issues.
=> Fix Bar SSR

website/src/data/components/line/defaults.ts, website/src/data/components/stream/defaults.ts, website/src/pages/area-bump/index.tsx, website/src/pages/boxplot/index.tsx, website/src/pages/bump/index.tsx, website/src/pages/heatmap/index.tsx, website/src/pages/marimekko/index.tsx, website/src/pages/scatterplot/index.js, website/src/pages/swarmplot/index.js
This PR will  the error appearing on the website when trying to expand any axis options "axisTop" "axisBottom" "axisLeft" "axisRight"
It solve the issue [#2503](https://github.com/plouc/nivo/issues/2503)
=> Fix: add initial property for truncateTickAt

packages/bar/src/Bar.tsx
Fix: https://github.com/plouc/nivo/issues/2574
=> fix: Add missing key to BarTotals

packages/bar/src/BarCanvas.tsx
Fix https://github.com/plouc/nivo/issues/2568
=> fix(bar): fix canvas grid lines not considering margin

packages/legends/src/svg/ContinuousColorsLegendSvg.tsx
fix https://github.com/plouc/nivo/issues/2581
=> fix(heatmap): do not spread key prop

packages/line/src/Line.tsx, packages/line/src/LineCanvas.tsx, packages/line/src/defaults.ts, packages/line/src/hooks.ts, packages/line/src/types.ts, website/src/data/components/line/props.ts
Fixes https://github.com/plouc/nivo/issues/2705 & https://github.com/plouc/nivo/issues/341
=> feat(line): allow using the point data to determine the point's color

packages/scales/src/symlogScale.ts, packages/scales/src/types.ts, packages/scales/tests/symlogScale.test.ts
Fixes https://github.com/plouc/nivo/issues/2685.
=> feat(scales): allow to define nice and round options for the symlog scale

packages/bump/src/bump/Bump.tsx, packages/bump/src/bump/ResponsiveBump.tsx, packages/bump/src/bump/defaults.ts, packages/bump/src/bump/types.ts, packages/bump/tests/Bump.test.tsx
Fixes https://github.com/plouc/nivo/issues/2619.
=> Fix bump typings

packages/axes/src/canvas.ts, packages/axes/src/components/Axis.tsx, packages/axes/src/components/AxisTick.tsx, packages/axes/src/types.ts, packages/polar-axes/src/CircularAxis.tsx, packages/polar-axes/src/CircularAxisTick.tsx, packages/polar-axes/src/RadialAxis.tsx, packages/polar-axes/src/RadialAxisTick.tsx, packages/polar-axes/src/types.ts, packages/theming/src/extend.ts, packages/theming/src/hooks.ts, storybook/stories/line/Line.stories.tsx, storybook/stories/line/LineCanvas.stories.tsx, storybook/stories/line/shared.ts, website/src/data/components/line/meta.yml, website/src/lib/chart-properties/axes.ts, website/src/lib/componentProperties.ts
Fixes https://github.com/plouc/nivo/issues/2633.
=> feat(axes): allow axes style overrides

packages/theming/package.json, pnpm-lock.yaml
=> fix(theming): add missing lodash dependency
