src/components/charts/sankey/Sankey.js, src/components/charts/sankey/SankeyLinks.js, src/components/charts/sankey/SankeyLinksItem.js, src/components/charts/sankey/SankeyNodes.js, src/components/charts/sankey/SankeyNodesItem.js, src/components/charts/sankey/props.js, stories/charts/sankey.stories.js
As discussed in https://github.com/plouc/nivo/issues/71, this adds onClick support for Sankey charts. onClick handlers are registered for both nodes and links and the onClick parameter order is aligned with the order of the bar and bubble charts.
=> feat(interactivity): add onClick support for Sankey

src/components/charts/bar/enhance.js
That was probably copy/pasted at some point. Not a bug, just something that doesn't need to happen twice.
=> fix(bar): getLabel is defined twice

src/components/charts/sankey/Sankey.js, src/components/charts/sankey/SankeyLabels.js, src/components/charts/sankey/SankeyLinks.js, src/components/charts/sankey/SankeyLinksItem.js, src/components/charts/sankey/SankeyNodesItem.js, src/components/charts/sankey/enhance.js, src/components/charts/sankey/props.js, stories/charts/sankey.stories.js
This uses the label handling that the bar chart already has and applies it to sankey charts.
Storyboard result:
=> feat(sankey): Support configurable labels

src/components/charts/sankey/Sankey.js, src/components/charts/sankey/SankeyLinks.js, src/components/charts/sankey/SankeyLinksItem.js, src/components/charts/sankey/SankeyNodes.js, src/components/charts/sankey/SankeyNodesItem.js, src/components/charts/sankey/props.js, stories/charts/sankey.stories.js
This is the last PR for issue https://github.com/plouc/nivo/issues/71. It will make tooltips configurable for Sankey nodes and links via two additional (optional) props:
```javascript
<Sankey
{...commonProperties}
nodeTooltip={node => <span>Custom tooltip for node: {node.id}</span>}
linkTooltip={node => (
<span>
Custom tooltip for link: {node.source.id} to {node.target.id}
</span>
)}
/>
```
In combination with the `theme` prop, is allows full control over tooltip content and style.
=> feat(sankey): Support complete configuration of the tooltips

src/components/charts/line/Line.js, src/components/charts/line/LineAreas.js, src/components/charts/line/props.js, stories/charts/line.stories.js
New property `enableArea` (and `areaOpacity`) was added to decorate Line charts.
=> feat(line): new prop enableArea was added to Line chart

yarn.lock
Nivo is affected by https://nodesecurity.io/advisories/566. This is also
reported by Gemnasium and the reason for the red flag within the README.
This change upgrades `@storybook/react` which transitively depends on
`hoek`:
```
$ yarn why hoek
yarn why v1.3.2
[1/4] 🤔  Why do we have the module "hoek"...?
[2/4] 🚚  Initialising dependency graph...
[3/4] 🔍  Finding dependency...
[4/4] 🚡  Calculating file sizes...
info Has been hoisted to "hoek"
info This module exists because "@storybook/react#request#hawk" depends on it.
info Disk size without dependencies: "28MB"
info Disk size with unique dependencies: "28MB"
info Disk size with transitive dependencies: "28MB"
info Number of shared dependencies: 0
✨  Done in 0.81s.
```
The changes within this PR are the result of executing:
```
yarn …
```
=> fix(security): Upgrade transitive hoek dep

.storybook/config.js, packages/nivo-bar/src/Bar.js, packages/nivo-bar/src/BarCanvas.js, packages/nivo-bar/src/BarItem.js, packages/nivo-bar/src/props.js, packages/nivo-bar/stories/bar.stories.js, packages/nivo-bar/stories/barCanvas.stories.js, packages/nivo-core/src/components/tooltip/BasicTooltip.js, packages/nivo-heatmap/src/HeatMap.js, packages/nivo-heatmap/src/HeatMapCanvas.js, packages/nivo-heatmap/src/HeatMapCellTooltip.js, packages/nivo-heatmap/src/ResponsiveHeatMap.js, packages/nivo-heatmap/src/ResponsiveHeatMapCanvas.js, packages/nivo-heatmap/src/props.js, packages/nivo-heatmap/stories/heatmap.stories.js
Similar to what I contributed before for the Sankey chart, this allows complete control over a tooltip for bar charts and heat maps. I also took the liberty of establishing a default way for tooltip overwrites within `BasicTooltip`.
=> Support configurable tooltips for bar charts and heat maps

packages/nivo-bar/index.d.ts
I based this off of #198 with some changes.
- I used the built in `Partial` mapped-type instead of marking all properties optional with `?`. This is why I separated out `data` property as it is required.
- Add types for Legend.
- Add types for Theme.
- There were a few types missing from `Axis` type in the Heatmap PR, this PR contains those.
Reference #197
=> Add TypeScript definitions for Bar package

packages/nivo-pie/index.d.ts
closes #206 
ref: #197 
I had to include the INivoLegendItem. Not sure if its possible to re-use definition files from other packages. If so when creating the legend definitions we could/should perhaps refactor this.
=> Definitions for Pie component

.storybook/config.js, packages/nivo-circle-packing/src/Bubble.js, packages/nivo-circle-packing/src/BubbleHtml.js, packages/nivo-circle-packing/src/BubbleHtmlNode.js, packages/nivo-circle-packing/src/interactivity.js, packages/nivo-circle-packing/src/props.js, packages/nivo-circle-packing/stories/bubble.stories.js, packages/nivo-circle-packing/stories/bubbleHtml.stories.js, packages/nivo-treemap/src/TreeMap.js, packages/nivo-treemap/src/TreeMapHtml.js, packages/nivo-treemap/src/TreeMapHtmlNode.js, packages/nivo-treemap/src/TreeMapNodeTooltip.js, packages/nivo-treemap/src/interactivity.js, packages/nivo-treemap/src/props.js, packages/nivo-treemap/stories/treemap.stories.js, packages/nivo-treemap/stories/treemapHtml.stories.js
This allows custom tooltips for bubble charts and treemaps.
=> feat(tooltips): add support for custom tooltips for bubble charts and treemaps

packages/nivo-bar/src/Bar.js, packages/nivo-bar/src/props.js, packages/nivo-core/src/components/axes/Grid.js, packages/nivo-core/src/lib/cartesian/axes.js
As I think that this feature was often requested in the past, I've added another option that was inspired by `tickValues`: `xGridValues` and `yGridValues`.
At first I thought that we could use the `tickValues` value from the `axis` prop, but since there could be two axis for one dimension, we need an extra option.
So this component `<Bar {...commonProps} axisLeft={{ tickValues: [0,50,100] }} gridYValues={[0,50,100]} />` would produce this chart:
If you're fine with this idea/my approach, I would like to add the props to all other components (I've just added it to the `Bar` component in the moment) and add tests :-)
=> [WIP] added option to define `gridValues`

packages/nivo-core/src/components/tooltip/BasicTooltip.js, packages/nivo-heatmap/src/computeNodes.js, packages/nivo-heatmap/src/props.js
When a NaN value is included in heatmap data, no errors appear but two warnings are raised:
* The prop `node.color` is marked as required in `HeatMapCellTooltip`, but its value is `undefined`.
* Received NaN for the `children` attribute. If this is expected, cast the value to a string.
This commit addresses both of these, and adds a `nanColor` prop to `HeatMap` to allow specifying the color used for a cell that is NaN (defaults to #000000).
=> fix(heatmap): better handling of NaN values

packages/nivo-line/src/LineDots.js
Supplying a formatting function to `dotLabelFormat` on the Line graph type
results in a prop type validation error, however the label is formatted
correctly.
The `getLabelGenerator` function is responsible for actually formatting
this label, and accepts a string or a function as a formatter.
=> LineDots labelFormat PropType can be string or function

packages/bar/src/Bar.js, packages/bar/src/BarItem.js, packages/bar/src/props.js, packages/bar/stories/bar.stories.js, packages/pie/src/Pie.js, packages/pie/src/PieSlice.js, packages/pie/src/props.js, packages/pie/stories/pie.stories.js, packages/scatterplot/src/ScatterPlot.js, packages/scatterplot/src/ScatterPlotItem.js, packages/scatterplot/src/props.js, packages/scatterplot/stories/scatterplot.stories.js
So, I added support for onMouseEnter and onMouseLeave, on _Bar_, _Pie_ and _Scatterplot_ at the moment. 
If everything looks ok to you I can add support to all the other types (all except Calendar maybe), in their SVG version (I don't think it's needed in the Canvas one, at least for now). 
Here is a simple example of use:
```jsx
<Pie
{...commonProperties}
onMouseEnter={(data, event) => {
console.log({ is: 'mouseenter', data, event }) // eslint-disable-line
}}
onMouseLeave={(data, event) => {
console.log({ is: 'mouseleave', data, event }) // eslint-disable-line
}}
/>
```
This allows to connect two or more charts (Eg. when I hover an element on one, the corresponding element on the second one highlights).
It does not interphere with the tooltip functionality.
=> Feat enterleave

packages/circle-packing/src/interactivity.js, packages/circle-packing/tests/Bubble.test.js
Hey there!
Great lib! I've been using this bubble chart for a project and it's great.
One issue though is you can't get the `node` data with an onClick handler if the 
chart's interactivity/zoom is disabled. I wrote a quick PR here addressing it.
- call the `onClick` function passed in to the chart in either case
- add test to confirm value sent in the click is correct
Thanks!
=> Send node data to onClick handler when isZoomable is false on Bubble Chart

packages/bar/src/BarCanvas.js
I just added `enableGridX` / `enableGridY` / `legends` options to `BarCanvas` component as SVG `Bar` component does. 
Here is how it looks (tested with storybook 😅) 
- Before 
- After
=> feat(bar) Add enableGridX / enableGridY / legends props to BarCanvas component

packages/line/stories/line.stories.js
Just added one more example "Custom line style" to show how we can customize line style using `layers` prop  e.g. dashed line
=> Add an example to show how we can make dashed line style using 'layers' prop

packages/bar/src/Bar.js, packages/bar/src/BarCanvas.js
Another trial to fix #111 or #218 
So the problem that I aim to fix here is, if some keys have `0` as value in first column, it doesn't generate legend at all even if other columns have non-zero value. 
Related conversation is also in #128 which is a first trial to fix this issue. I saw #219 as well and I understand there might be more cases we can improve. 
But I think many ppl including me, this missing legend with zero value in 1st column issue is more urgent I think. 
tl; dr 
Also applied in Canvas
=> Fix missing legend in Bar chart 

packages/scatterplot/src/ScatterPlotCanvas.js, website/src/components/charts/scatterplot/ScatterPlotCanvas.js
=> Fix wrong legend item color in ScatterPlotCanvas

packages/scales/index.d.ts
otherwise some storybook examples are failling to compile with typescript
=> added the day value on the TimeScale interface

packages/bar/src/BarItem.js
Bar chart allow to use a function that returns a `<tspan>` tag, but BarItem's ProptTypes expect to receive a string only, showing a warning in the browser development console.
System:
- SO: Windows 10 Enterprise
- Browser: Chrome Version 70.0.3538.110 (Official Build) (64-bit)
- Nivo/Bar:  0.51.5
How to reproduce:
- Use the bar package
- Create a `Bar` or `ResponsiveBar` element
- Set the `labelFormat` property to `d => <tspan>custom {d}</tspan>}`
- Run the app and check the browser development console for message `Warning: Failed prop type: invalid prop 'label' supplied to 'baritem'`.
=> fix(bar): Allow BarItem label property to accept React.Element

packages/bar/src/BarCanvas.js
Fixes https://github.com/plouc/nivo/issues/419
I tried `tickValues` setting in `ScatterPlotCanvas` chart (as another example of canvas chart) and found that the setting works in there.
I think it's because two canvas chart components use different `renderAxesToCanvas` util func.
- ScatterPlotCanvas : `renderAxesToCanvas` is come from  `@nivo/axes` -> https://github.com/plouc/nivo/blob/master/packages/scatterplot/src/ScatterPlotCanvas.js#L11
- BarCanvas : `renderAxesToCanvas` is come from  `@nivo/core` -> https://github.com/plouc/nivo/blob/master/packages/bar/src/BarCanvas.js#L13
As you can see `nivo/core`'s `renderAxesToCanvas` doesn't accept `tickValues` whereas `nivo/axes`'s does. 
- `nivo/axes/canvas` -> https://github.com/plouc/nivo/blob/master/packages/axes/src/canvas.js#L22
- …
=> [BarCanvas] Fix tickValues setting in BarCanvas chart

packages/core/index.d.ts, packages/line/index.d.ts, packages/line/src/Line.js
Allow showing tooltips from custom layers.
Edit: BasicTooltip and TableTooltip was not exported from ts-definitions so added that as well.
=> feat(line): pass showTooltip and hideTooltip functions to custom layers

packages/axes/src/canvas.js, packages/circle-packing/src/BubbleCanvas.js, packages/heatmap/src/HeatMapCanvas.js, packages/heatmap/src/canvas.js, packages/pie/src/canvas.js, packages/treemap/src/TreeMapCanvas.js
I just saw how it's enabled in Chord Canvas chart https://github.com/plouc/nivo/commit/c4f29c51408b9be6ad513d0eaf9e303ac12a19eb
using `theme`
and applied in several Canvas packages 
- Canvas/Axes (Ticks)
- PieCanvas (Label / Radiar)
- Heatmap (Label)
- TreeMap (Label)
- Bubble (Label)
I tried some in storybook (I built it locally)
- Ticks 
- Label in heatmap cells
=> Support custom font family setting in canvas charts / axes

packages/scatterplot/src/ScatterPlotCanvas.js
Fixes https://github.com/plouc/nivo/issues/370
=> Set pointer as 'normal' not crosshair in ScatterPlot canvas chart

packages/legends/src/svg/LegendSvgItem.js, packages/stream/stories/stream.stories.js
I think #151 came back with a few non-scoped lodash imports. Prior #191.
=> fix(lodash): use scoped imports

packages/sankey/src/SankeyLinksItem.js, packages/sankey/stories/sankey.stories.js
This PR aims to make it much easier to customize node and link colorings for the sankey plot, to be able to create a plot like this
Now one can customize link gradients from the node color when using enable gradient by adding the startColor and endColor properties to each link's data. Otherwise, this will default to the color of each node.
=> Feature: Decouple Sankey Node coloring and Link coloring

packages/core/src/components/axes/Grid.js, packages/core/src/lib/cartesian/axes.js, packages/line/src/props.js
This commit adds gridCount/integer support to `gridXValues` and `gridYValues` for line charts. This allows for grid lines and axes ticks to be calculated the same when using a number that is passed. For example:
```javascript
<ResponsiveLine
axisRight={{
tickValues: 6,
}}
gridYValues={6}
...
/>
```
I tried to follow all of the contributing guidelines, happy to contribute to a great library!
=> Add number support to gridXValues and gridYValues on Line

website/src/components/pages/Faq.js
Currently, there are some cases that the component doesn't render because it finds that the height is 0. You will see an output like
This can be avoided by providing the desire height for the responsive chart
=> GH-122: Add new faq when responsive component is not render

packages/bar/index.d.ts
The legendPositions possible values are ['start', 'middle', 'end'] [Example](https://nivo.rocks/bar/). I'll make another PR for documentation update too.
=> Update type definition of Axis

packages/line/index.d.ts
Hello! 👋
I noticed the type definition for `LineSliceData` was not matching the actual implementation. Here what I saw in the console:
Looking at the code also confirmed my suspicions
https://github.com/plouc/nivo/blob/master/packages/line/src/LineSlices.js#L39-L73
It's a quick fix, but do let me know if there's something else
=> Update TS declaration for LineSliceDate

website/src/components/guides/axes/AxesLegend.js
The documentation still says `legendPosition must be one of: start, center or end` ([Source](https://nivo.rocks/guides/axes)) so it should be updated too.
This is related to [PR 475](https://github.com/plouc/nivo/pull/475)
=> Update documentation for legend

website/src/components/charts/bar/props.js
Added the formatLabel prop to the Bar chart documentation. I was looking for this and didn't notice it in the diverged staked story, and didn't see the prop was an option until I saw the conversation in #64 . Figured this might save someone some time in the future.
=> doc(Bar): Add labelFormat prop to Bar docs

package.json, packages/sankey/index.d.ts, packages/sankey/package.json, packages/sankey/src/Sankey.js, packages/sankey/stories/sankey.stories.js, yarn.lock
Update @nivo-sankey to point to neilrackett's d3-sankey fork, exposing his addition of the nodeSort method by adding the sort parameter to Sankey. (Note that the head fork d3/d3-sankey has been inactive for over a year).
This allows the developer to render the nodes in the order submitted, or in a custom sorted order based on any metric they attach to the nodes. Note that in my PR I am purposely allowing the sort method to be optional.
Default
With reverse sort order function property
Function that was attached for the sankey_stories.js file
```javascript
let minNodeValueOnTop = (nodeA, nodeB) => { 
if (nodeA.value < nodeB.value) return -1 
if (nodeA.value > nodeB.value) return 1 
return 0 
}
```
=> Feature: Add orderability to Sankey Nodes

packages/scatterplot/src/ScatterPlotCanvas.js
Referencing https://github.com/plouc/nivo/issues/507
An alternative solution would be to check for Truthyness of the point object.
I.E. At line 122
```
if (point) { ...
```
It's unclear to me at this point which is a better solution.
=> Minor bug fix for when clicking in canvas margin

packages/core/index.d.ts, packages/core/src/theming/defaultTheme.js, packages/tooltip/src/components/BasicTooltip.js
This request is related to issue #588. It simply moves chipStyles from tooltip component to theme, which allows adding custom properties to tooltip chips if necessary.
=> Chip theme

packages/axes/src/compute.js, packages/axes/tests/compute.test.js, packages/scales/src/timeScale.js
If I am to disable UTC for the scale, then I would expect the tick values to also not use UTC. It looks like from the code we always use the UTC helpers when generating tick values. I'm not sure if this is the best way to pass that option from the `scale` package to the `axes` package. So feel free to tell me to do it a different way.
Here is my first CodeSandbox with my simple test case, and you can see the values are incorrect on the ticks. Also the first tick is missing a value. https://codesandbox.io/s/jyz1h
I used `patch-package` to apply the code changes in the PR here, but those weren't respected in CodeSandbox. I have a deployed version here (https://csb-jyz1h-crmzrjqkcn.now.sh/) where you can see the tick values are correct, including the first point.
To view the source for the …
=> Respect useUTC option on x/y scale property

packages/geo/index.d.ts
I'm getting an error when running ResponsiveChloropleth when using it without a domain prop. Typescript should have caught this, since it is a required prop, but it didn't because it's not in the index.d.ts file.
=> Fix domain not in index.d.ts file, even though it is required

packages/line/index.d.ts
Adding a missing typing for the tooltip on the Line and ResponsiveLine components.
[TS error of the missing property definition](https://i.imgur.com/EuMHjYg.png)
=> Adding a tooltip typing to the LineProps interface (Line/ResponsiveLine)

packages/line/index.d.ts
Added missing typings. Done accordingly to:
https://github.com/plouc/nivo/blob/master/packages/axes/src/components/Grid.js#L51
https://github.com/plouc/nivo/blob/master/packages/line/src/Line.js#L139
=> added gridXValues and gridYValues to line typings

packages/legends/src/svg/LegendSvgItem.js
This simple modification adds access to the legend id in the symbolShape property. This is useful because it enables the possibility of rendering a custom icon next to each legend, based on the id. It is then possible to implement a toggling button on each legend, which can show and hide part of the data from the graph.
=> feat: add id to symbolShape

packages/bar/index.d.ts
contributes to #197 where borderColor was missing from TypeScript definitions in nivo/bar. From what I could see in the documentation borderColor has the same definitions as labelTextColor so I just simply reused them
=> add borderColor type definition for nivo/bar

packages/calendar/src/enhance.js
I needed a custom `color` on the calendar heatmap based on my scale so I added this functionality. I have made it successfully work in my codebase. 
I need more clarity on what needs to be changed and if there's a better way to do this rather than what I have currently done. 
It also needs an update in the documentation.
Resolves #693
=> Added custom `colorScale`

packages/calendar/index.d.ts
I have noticed that these classes were never exported and I could not import them in typescript. After adding these 2 lines it was working very well. We had big data to display and with the svg canvas it was very laggy. As soon as I exported these 2 classes, calendar was displayed in canvas and the response speed was amazing!
=> Added export classes for canvas calendar

packages/scales/index.d.ts
After some messing around with Nivo and line charts, I had a issue where I discovered the dates I was passing in were being converted to the clients timezone, even though I wasn't supplying a timezone with the date and these dates I was passing in were actually already correct. To get around this we discovered a `useUTC` option which we set to `false`. 
Although it seems like its missing from the types.
=> Add `useUTC` to types

packages/line/index.d.ts
The `pointSymbol` is missing in the line typings. Fixes the following error:
=> Add missing pointSymbol prop to line typings

packages/core/src/components/cartesian/markers/CartesianMarkers.js, packages/core/src/components/cartesian/markers/CartesianMarkersItem.js, packages/line/src/props.js
When using a Line chart with time in the X axis, passing a date as a marker's x value works but raises a PropTypes warning. This change allows dates in the markers' values.
=> Fix PropType for Line markers when using dates in the X axis.

website/src/data/components/bar/props.js
The fix is based on the same field in bubbles which does properly use markdown, this can be found [here](https://github.com/plouc/nivo/blob/52feccbfdf9c65d01238edffe83efa75eb6e248a/website/src/data/components/bubble/props.js#L235).
=> fix: broken markdown description of the 'labelFormat' property (Fixes #747)

packages/tooltip/index.d.ts
- removed theme= from Basic/TableTooltip
- define Chip
=> Update tooltip TypeScript types.

packages/tooltip/src/hooks.js
Related to #580
Hello. Thanks for your hard work and great skill writing this library! 🙇 
This PR may not be good enough to merge, but I wanted to propose it anyway, given [this comment](https://github.com/plouc/nivo/issues/617#issuecomment-508116675), which suggests that this change (or something like it) could be appropriate. This seems hack-y to me, but I've been using this patch in my own application, and I thought it would be worth sharing. Opening this PR seemed like a good way to share this, even if the PR itself is not mergeable.
=> keep the tooltip inbounds

packages/line/src/LineCanvas.js, packages/line/stories/LineCanvas.stories.js
This PR add support of xFormat/yFormat in LineCanvas chart. Currently Tooltip in LineCanvas could not be used with time series data due to missing option to use formatter
=> Add option to format x/y values in tooltip

packages/bar/src/props.js
Adds BarChart PropTypes to match changes made in https://github.com/plouc/nivo/pull/391
=> Add numbers to BarChart PropTypes for gridXValues and gridYValues

packages/bar/src/Bar.js, packages/bar/src/compute/legends.js
When using the `vertical stacked bar` chart with a `row` legend, the legend order was in reverse. This PR fixes this issue by preventing the legend data to be reversed, when it is in `row` format. 
**Before**
**After**
=> Fix bar legend order

packages/scatterplot/src/ScatterPlot.js
These props are defined here: https://nivo.rocks/scatterplot/
but they're not actually in the ScatterPlot component.
=> add grid{X/Y]Values to ScatterPlot

packages/bar/src/Bar.js
In the same vein as #425, expose `showTooltip`/`hideTooltip` functions to custom layers in the bar chart.
Resolves #914
=> feat(bar): pass showTooltip and hideTooltip functions to custom layers

packages/line/index.d.ts
=> bug(line): add missing layer 'crosshair' to TypeScript definition

packages/scatterplot/package.json, packages/scatterplot/src/ScatterPlot.js, packages/scatterplot/src/ScatterPlotAnnotations.js, packages/scatterplot/src/hooks.js, packages/scatterplot/src/props.js, packages/scatterplot/stories/ScatterPlot.stories.js, yarn.lock
Adds support for putting annotations over a scatterplot. This was mostly taken from the swarmplot implementation.
Connects #125.
=> Add support for annotations on scatterplots

website/src/components/guides/gradients/GradientsExample.js
A Closed bracket was missing at the code block in gradients guide.
Please check out [https://nivo.rocks/guides/gradients](https://nivo.rocks/guides/gradients)
=> Add closed bracket in gradients example code

packages/scatterplot/index.d.ts, tsconfig.json
Fix for #856.
The `CustomTooltip` typing from scatterplot was creating an error in Typescript projects with the `noImplicitAny` compiler optoin enabled. This error was because the argument to the `CustomTooltip` lambda wasn't being typed:
```ts
export type CustomTooltip = ({ node: Node }: /* NEEDS TYPING */) => React.ReactNode
```
So the fix is to create a specific `TooltipProps` for the argument and enable `noImplicitAny` across the project to prevent regressions.
=> fix(scatterplot): fix no implicit any error on CustomTooltip

packages/bar/index.d.ts, packages/pie/index.d.ts
Supersedes https://github.com/plouc/nivo/pull/868, covers for some of https://github.com/plouc/nivo/pull/280 (Bar & Pie, not ScatterPlot)
=> fix(types): improve typings for onMouseLeave/Enter in Bar/Pie

packages/scales/index.d.ts, packages/scales/src/timeScale.js
* updated the TypeScript definition to allow for `min` and `max` properties in the `TimeScale`
* updated the implementation to behave correctly with custom `min`/`max` values when the `TimeScale` has `format` property specified.
=> fix(scales): fix timeScale min/max values and typings

packages/scatterplot/index.d.ts
serieId is a property on `Node.data` not `Node` itself:
From compute.js
```js 
export const computePoints = ({ series, formatX, formatY }) => {
return series.reduce(
(agg, serie) => [
...,
...serie.data.map((d, i) => ({
...,
data: {
...,
serieId: serie.id
},
})),
],
[]
)
}
```
=> fix(scatterplot): fix serieId typing

packages/line/index.d.ts, packages/line/src/Areas.js, packages/line/src/Line.js, packages/line/src/props.js, packages/line/stories/line.stories.js, website/src/data/components/line/meta.yml, website/src/data/components/line/props.js
Add Gradient Support to Line Areas
=> feat(line): add gradient support to line areas

website/src/components/HeaderNav.js, website/src/pages/references.js
This PR implements a reference page to the website, as asked at issue  #261 .
Closes #261
=> feat(website): add a references page to the website

packages/bar/index.d.ts
Currently the props: gridXValues & gridYValues can't be used in a TypeScript project.
This PR adds them to the type definition.
=> fix(bar): add missing grid value types

packages/bump/src/area-bump/AreaBump.js, packages/bump/src/area-bump/props.js, packages/bump/stories/bump.stories.js, website/src/data/components/area-bump/props.js, website/src/pages/area-bump/index.js
=> feat(bump): add support for defs/fill properties to AreaBump

packages/bump/index.d.ts
It looks like I missed this in #926 sorry - it currently complains about a missing type for `defs`:
```
Property 'defs' does not exist on type 'IntrinsicAttributes & IntrinsicClassAttributes<ResponsiveAreaBump> & Readonly<AreaBumpSvgProps> & Readonly<...>'.
69 |             colors={colors}
70 |             data={data}
> 71 |             defs={defs}
|             ^
72 |             endLabelTextColor={labelColor}
73 |             fill={fill}
74 |             startLabelTextColor={labelColor}
```
=> fix(bump): Add types for defs to AreaBumpSvgProps

packages/calendar/index.d.ts, packages/calendar/src/compute.js, packages/calendar/src/enhance.js, packages/calendar/src/props.js, packages/calendar/stories/calendar.stories.js, website/src/data/components/calendar/props.js, website/src/pages/calendar/canvas.js, website/src/pages/calendar/index.js
This PR adds the prop `monthSpacing` to `@nivo/calendar` as an option to add spacing between months in the rendered output.
=> feat(calendar): add monthSpacing prop

packages/legends/src/svg/LegendSvgItem.js
This fixes #814 - or so I hope
The fill color of the legend text is currently not themeable
because the fill from the theme is always overwritten by either
the style from the local component state (my understanding is
that this style is from mouse hover effects) or the value of
the `textColor` prop which defaults to `black`.
This line would still allow the local state to take precendence,
but would then pick the theme's legend text fill color as a backup
and only then resort to the `textColor` props.
Disclaimer: This is the first time ever I look at the Nivo code
so there might be more subtle things that I'm overlooking.
=> fix(legends): Respect theme fill color

packages/radar/index.d.ts
I want to use nivo/radar like below link in typescript code.
In that example code, custom label component return react element.
[nivo/rader: custom-label-component](https://nivo.rocks/storybook/?path=/story/radar--custom-label-component)
but, because of Type Declaration, I can't use custom label component for nivo/radar.
So, I fix packages/radar/index.d.ts code. Could you review it?
=> fix(radar): Add return type of GridLabelCustomFunction

packages/bullet/src/Bullet.js
- Adds support for < 0 values in bullet graphs by including a value < 0 in the range
- First time committing to this repo, not sure if there's anything else I should do, here's an example where this would be useful (using a bullet graph to display standard deviations or z-scores)
=> feat(bullet): support ranges that support < 0

CONTRIBUTING.md
Finding out how to launch tests was only a quick look at `Makefile` away, but I think it makes sense to have it in the CONTRIBUTING docs—it also has the benefits of stating that there _are_ tests to check your PR against.
=> chore(docs): Add Testing section in CONTRIBUTING.md

packages/line/src/Lines.js, packages/line/src/Points.js, packages/line/tests/__snapshots__/Line.test.js.snap
Fixes #1051 
Reversing the `lines` and `points` array makes the lines and points belonging to lower series appear on top—and makes the graph less misleading.
See this before/after screenshot comparison (the area of interest is the red and yellow lines at the NG and LS ticks):
**Before**
We get the impression that the yellow line is increasing, although its value is 0.
**After**
We get the right impression (the red line is increasing).
=> fix(line): change points ordering on stacked lines

.storybook/config.js, CONTRIBUTING.md, packages/network/src/AnimatedNodes.js, packages/network/src/Network.js, packages/network/src/NetworkNodeTooltip.js, packages/network/src/Node.js, packages/network/src/StaticNodes.js, packages/network/stories/network.stories.js, website/src/data/components/network/props.js
Hi @plouc, great project here; thanks for all your great work!
Added Tooltips to the Network graph. Also, added it to the storybook to make further dev a little easier. 
Please let me know if you have any feedback or would like to see anything different.
PS Added the prop documentation to the website as well.
=> feat(network): add support for tooltips

packages/generators/src/index.js, packages/generators/src/network.js, packages/network/stories/network.stories.js, website/src/pages/network/canvas.js, website/src/pages/network/index.js
Moves this from the website workspace so it can be shared with storybook.
=> feat(generators): add network data generation

packages/pie/index.d.ts
Seems like the pie tooltip typing is broken, I replaced `StatelessComponent` with `FunctionComponent`, since `SC` is deprecated, also the label seemed missing, I added its typing according to the docs.
EDIT: typo
=> fix(pie): tooltip props typing

packages/sankey/src/hooks.js, packages/sankey/stories/sankey.stories.js
When implementing a sankey diagram using nivo, we experienced an issue with the sort order of the diagram's links which this PR fixes.
Our requirement is that nodes are ordered in a specific order (in our case alphabetically by their label), so we went with the `sort="input"` prop.
The following example illustrates the problem and uses the following data:
```js
{
nodes: [
{ id: 'foo_left', color: '#ff0000' },
{ id: 'bar_left', color: '#0000ff' },
{ id: 'baz_left', color: '#00ff00' },
{ id: 'foo_right', color: '#ff0000' },
{ id: 'bar_right', color: '#0000ff' },
{ id: 'baz_right', color: '#00ff00' },
],
links: [
{ source: 'foo_left', target: 'bar_right', value: 5 },
// This is commented in after the first screenshot!
// { source: 'foo_left', target: 'baz_right', value: 5 },
{ source: …
```
=> Sankey: Sort links by input if nodes are sorted by input order

packages/axes/index.d.ts, packages/axes/src/components/Axis.js, packages/axes/src/props.js, packages/bar/index.d.ts, packages/bar/src/Bar.js, packages/bar/src/props.js, packages/core/src/components/SvgWrapper.js
This PR allows for improved a11y on the charts that use the `<SvgWrapper>` component.
Currently, `<SvgWrapper>` has the default role on the tag set to `role="img"`. This makes the chart inaccessible to screen readers. Adding a role prop to the `<Bar>` component, and passing through to `<SvgWrapper>` allows for accessibility by optionally setting the role to `group`. 
There's also the addition of the `ariaHidden` prop to the `Axis` component. When this value is set to `true` and the chart is accessible, it will allow the user to skip over the values of the axes when using a screen reader which can improve the user experience.
=> Add changes to allow for improved accessibility on charts.

packages/line/stories/line.stories.js, packages/scales/index.d.ts, packages/scales/src/compute.js, packages/scales/src/index.js, packages/scales/src/symlogScale.js, packages/scatterplot/stories/ScatterPlot.stories.js, packages/scatterplot/stories/ScatterPlotCanvas.stories.js
Thank you for the great library!
Lately we needed to render some graphs using logarithmic scale, but found out that `d3-scale`'s logarithmic scale is not very well suited for data having a wider range. For those use cases one can use symlog scale which "offers a bi-symmetric log transformation, suitable ‘for wide-range data’. Its domain can span several orders of magnitude, with negative as well as positive values." `d3-scale` has also API for that.
Add support for [symlog scale](https://github.com/d3/d3-scale#symlog-scales). The code is heavily inspired by a PR adding the support for logarithmic scale: https://github.com/plouc/nivo/pull/378
Compared to logarithmic scale PR, no safe-guarding for zero or negative values is needed since the scale accepts both.
I added relevant stories to …
=> feat(scales): Add support for symlog scale

packages/core/index.d.ts
Updates the Theme type to match the default theme object here:
https://github.com/plouc/nivo/blob/c443bc08b3abc8fa316e2ee78a6cc7dcded4c968/packages/core/src/theming/defaultTheme.js#L9
Otherwise passing the default theme object to the theme prop of ResponsiveScatterPlot results in a typescript error.
=> fix(core): Add missing Theme types to match default theme object

packages/scatterplot/index.d.ts
Adds support for DerivedNodeProp<number> so when a function is passed to nodeSize the id of the node can be referenced. The current implementation uses only DerivedDatumProp<number> and the Datum type only has x and y fields where as Node also contains its id.
Also, the nivo docs at https://nivo.rocks/scatterplot/ specify "it will receive the current node and must return a number" which is consistent with the proposed type.
=> fix(scatterplot): Support DerivedNodeProp for nodeSize prop

packages/core/index.d.ts, packages/swarmplot/index.d.ts
When implementing custom layers I noticed that the Pattern helpers were not being exported in the type def which caused us to have to use `@ts-ignore` in our code base. I also noticed when working with swarmplots the type def also appeared to be slightly off. I propose two changes in this PR, the first being to export the pattern helpers in the type definition of @nivo/core and the second to give layers a real definition instead of `any[]` in `@nivo/swarmplot`. If anything is not correct please let me know and I will be more than happy to fix it.
=> fix(core / swarmplot): Improve core and swarmplot typedefs

packages/bar/index.d.ts, packages/swarmplot/index.d.ts
Fixes #1155 
**Changes:**
- Change `data` prop type to `BarExtendedDatum`
- Remove `color` field in `data` prop's type - it doesn't exist in `data` prop
- Create `BarTooltipDatum` to pass `color` type to tooltip props along with
`BarExtendedDatum`
- Add `SVGRectElement` to `BarMouseEventHandler` generic type
- Update deprecated `React.StatelessComponent` to `React.FC`
=> fix(bar): Fix BarItemProps types

packages/annotations/src/AnnotationLink.js, packages/bump/src/area-bump/Area.js, packages/bump/src/bump/Line.js, packages/core/index.d.ts, packages/core/package.json, packages/core/src/hooks/index.js, packages/core/src/hooks/useAnimatedPath.js, packages/funnel/src/Part.js, packages/line/src/Areas.js, packages/line/src/LinesItem.js, packages/parallel-coordinates/src/ParallelCoordinatesAxisDensityPoly.js, packages/parallel-coordinates/src/ParallelCoordinatesLine.js, packages/radar/src/Radar.js, packages/radar/src/RadarGrid.js, packages/radar/src/RadarGridLevels.js, packages/radar/src/RadarShapes.js, packages/sankey/src/SankeyLinksItem.js, packages/stream/src/StreamLayer.js, yarn.lock
Animating paths don't work well with `react-spring` as they did previous with `react-motion`. I've created a custom hook that can be used to animate the paths properly.
This might be charts that support animating `curve` prop that crash, others might work correctly. The when trying to animate a curve, `react-spring` receives different size paths and tries to split strings and crashes because the lengths don't match.
I've added a list of charts below that contain `animated.path` component and will check each individually and either push fixes or check the box to ensure it is working properly.
Close #1170 
Close #1171
------
TODO:
=> Fix react-spring handling animating paths

package.json, yarn.lock
For some reason I keep having to do this locally, but the deployed version is fine. Better to do this now so we avoid problems in the future
=> fix(storybook): always pull latest version of generators package

packages/core/src/theming/defaultTheme.js, packages/legends/tests/svg/LegendSvgItem.test.js, packages/legends/tests/svg/__snapshots__/LegendSvgItem.test.js.snap
This will still get populated from extendDefaultTheme and will respect when the user provides a theme.textColor property
Close #1179
=> fix(theme): remove default fill for legends.text theme

packages/bar/index.d.ts, packages/bar/package.json, packages/bar/src/Bar.js, packages/bar/src/compute/grouped.js, packages/bar/src/compute/stacked.js, packages/bar/src/props.js, packages/bar/stories/bar.stories.js, website/src/data/components/bar/meta.yml, website/src/data/components/bar/props.js, website/src/pages/bar/index.js
- Cleaned up and reduced duplication in compute grouped/stack functions
- Removed mutation in compute code and made it more functional
- Added story with knob to show difference between linear/symlog
- Updated website with valueScale prop
=> feat(bar): add ability to set scale config via `valueScale` prop

packages/tooltip/src/components/TooltipWrapper.js
This closes #1184 - tooltips not being shown the first time a data point is tapped on a touch device.
The issue seemed to stem from how the code was setting the transform values. On the first event, `hasDimension` was false so the transform value wasn't being set. This change sets the transform value the first time the event is fired so it displays correctly. I also got rid of the opacity property since I didn't see a scenario where it should be set to 0 after this change, but let me know if I missed anything and I can add that back.
I did go through every chart type in the storybook and all of the tooltips seemed to render and hide themselves appropriately.
=> fix(tooltip): Show tooltip on first tap for touch devices

packages/bar/src/compute/grouped.js, packages/bar/src/compute/stacked.js
I know this is a hot topic and I know several other contributors made PRs adding options to change this behavior, but I think we should not be filtering out bars which would otherwise not be rendered.
I've put together a CodeSandbox comparing with 4 other charting libraries which all do not have this behavior: https://codesandbox.io/s/epic-sanne-hf3ef?file=/src/App.js
Also, I'm not sure I see the difference if the bar is not included versus not rendered. The bandwidth will remain the same since it is calculated over the entire data set, before we calculate the individual bars, so I don't see the harm in keeping this in the data.
@plouc would love to hear your thoughts on this.
Close #720 
Close #1061 
Close #1057 
Close #454
Close #591
Close #957
Close #1031
Close #986
=> fix(bar): include bars with zero height/width

packages/bump/package.json
fix https://github.com/plouc/nivo/issues/1198
=> fix(bump): add missing @nivo/axes module to dependencies

packages/bar/src/compute/grouped.js
=> fix(bar): prevent missing values causing bad scales

packages/bar/src/index.js
Add additional export of the default BarItem so that it can be used as a base BarComponent.
The need arose out of wanting to overlay text around the default BarComponent without having to rewrite the whole thing on my own.
Please consider this small change.
=> Update exports in Bar package to include the BarItem

packages/annotations/package.json, packages/axes/package.json, packages/bar/package.json, packages/bullet/package.json, packages/bump/package.json, packages/calendar/package.json, packages/chord/package.json, packages/circle-packing/package.json, packages/colors/package.json, packages/core/package.json, packages/funnel/package.json, packages/generators/package.json, packages/geo/package.json, packages/heatmap/package.json, packages/legends/package.json, packages/line/package.json, packages/network/package.json, packages/parallel-coordinates/package.json, packages/pie/package.json, packages/radar/package.json, packages/sankey/package.json, packages/scales/package.json, packages/scatterplot/package.json, packages/stream/package.json, packages/sunburst/package.json, packages/swarmplot/package.json, packages/tooltip/package.json, packages/treemap/package.json, packages/voronoi/package.json, packages/waffle/package.json
motivation:
- on npmjs.org you can click a link in the sidebar to go to the repo (compare [@nivo/bar](https://npm.im/@nivo/bar) with [react](https://npm.im/react))
- dependency upgrade tools like renovate and dependabot can link to the repo
-  dependency upgrade tools like renovate and dependabot can find the CHANGELOG file from the source repo and show include the relevant section in the PR
=> add repository field to every package.json

packages/bar/src/BarCanvas.js
`valueScale` prop has been added to the SVG Bar but not to the canvas version. This PR adds the prop and the default values.
This fixes #1273.
CC @wyze
=> fix(bar): add new prop valueScale to BarCanvas

packages/bar/src/BarCanvas.js, packages/bar/src/ResponsiveBarCanvas.js, packages/bar/stories/responsivBarCanvas.stories.js, packages/line/src/LineCanvas.js, packages/line/src/ResponsiveLineCanvas.js, packages/line/stories/LineCanvas.stories.js, packages/line/stories/ResponsiveLineCanvas.stories.js
This PR adds the ability to get the underlying `<canvas />` of a chart using a ref.
This feature is useful if you want to allow the user to download a chart image.
This fixes only part of #906 as it only handles the normal and responsive version of the LineCanvas and BarCanvas.
=> feat: add ref to access the underlying canvas

package.json, packages/annotations/package.json, packages/axes/package.json, packages/bar/package.json, packages/bullet/package.json, packages/bump/package.json, packages/calendar/package.json, packages/chord/package.json, packages/circle-packing/package.json, packages/colors/package.json, packages/funnel/package.json, packages/geo/package.json, packages/heatmap/package.json, packages/legends/package.json, packages/line/package.json, packages/marimekko/package.json, packages/network/package.json, packages/parallel-coordinates/package.json, packages/pie/package.json, packages/radar/package.json, packages/sankey/package.json, packages/scatterplot/package.json, packages/stream/package.json, packages/sunburst/package.json, packages/swarmplot/package.json, packages/tooltip/package.json, packages/treemap/package.json, packages/voronoi/package.json, packages/waffle/package.json, scripts/bump-peer-deps.js
This should run on publish automatically. I did run it to increment all the outstanding changes, maybe we can do it in a separate commit. It should only increment it when the core package version changes and out of sync with any package that has a peerDependency on core.
=> chore(build): add version script to bump peer dependencies on new version

packages/core/index.d.ts
Add missing `Theme` properties back that were inadvertently removed with `@nivo/line` version `0.64.0`
- background
- fontFamily
- fontSize
- textColor
=> fix(core): add missing properties back to theme type

packages/core/package.json, scripts/bump-peer-deps.js
This should work for any peer + dev dependency that starts with '@nivo' and detects a version change. It uses devDependency as the true source since that is what lerna bumps when it is publishing.
Also added the current version of tooltip to core, so next time it runs you will see that get bumped.
=> chore(build): bump any nivo peer dep on version mismatch

packages/bar/src/Bar.js, packages/bar/src/compute/common.js, packages/bar/src/compute/grouped.js, packages/bar/src/compute/stacked.js, packages/bar/tests/Bar.test.js
=> fix(bar): fix stacked bars when key is missing

packages/bar/index.d.ts, packages/bar/src/Bar.js, packages/bar/src/BarCanvas.js, packages/bar/src/compute/common.js, packages/bar/src/compute/grouped.js, packages/bar/src/compute/stacked.js, packages/bar/src/props.js, packages/bar/tests/Bar.test.js, packages/scales/index.d.ts, packages/scales/src/bandScale.js, packages/scales/src/index.js, packages/scales/src/indexedScale.js, website/src/data/components/bar/props.js, website/src/pages/bar/api.js, website/src/pages/bar/canvas.js, website/src/pages/bar/index.js
I noticed that `ResponsiveBar` charts with many, narrow bars were varying in width. The `svg` container was the correct width, but the bars within it were offset from the left/right edges.
Screencap:
After some digging, I narrowed it down to the use of `d3-scale.scaleBand.rangeRound()` within `Bar`'s `common.js::getIndexedScale()`. This diff puts this nicing behavior behind a `nice` prop, which defaults to `true` to maintain current functionality unless a developer opts out with `nice=false`.
The above test with `nice=false`:
I didn't add anything to the Bar demo site; I can if you like, but this prop feels niche / edge-case enough that it may not need to be surfaced in the demo site.
=> Add the ability to round bar index scale

packages/bar/index.d.ts
Switching BarLayerType typescript type definition from enum to a string union as discussed in #1322
=> feat(bar): typescript - uses string unions to define BarLayerType

package.json, packages/bullet/package.json, packages/colors/package.json, packages/marimekko/package.json, packages/pie/package.json, packages/sunburst/package.json, packages/tooltip/package.json, scripts/generate-changelog.js
It was pointed out that after the last release, the peerDependencies still weren't updated correctly. If we go look at https://unpkg.com/browse/@nivo/colors@0.66.0/package.json we can see indeed, peer dependencies are still at 0.65.0 for @nivo/core. It also has the `gitHead` field that points to the commit, https://github.com/plouc/nivo/commit/1f6cb2c933d1a319f223ea5509f12e17a952addc, which _does_ include the correct peer dependencies.
So, we are going to run the script in 2 different lifecycle methods, `version` and `prepublishOnly`. Also, note that the generated changelog was not in that commit, so updated the script to stage it for commit.
Unrelated, but the build includes the `tsconfig.tsbuildinfo` from typescript for our typescript packages, so I added an exclude in the `files` field …
=> chore(build): workaround lerna issues

packages/bump/src/area-bump/hooks.js, packages/bump/src/bump/hooks.js
Please have a look at the original issue described in #1301 and at the commit message descriptions of the two first commits of this PR for more details.
The fix can be observed through storybook or the website. In both cases, hovering over the AreaBump chart will prior to this PR do nothing, and after this PR correctly trigger active/inactive styles on the chart.
=> Fix for Area Bump chart problems in #1301

packages/scales/index.d.ts, packages/scales/src/linearScale.js, packages/scales/tests/linearScale.test.js
Optional ability to tell a linear scale to clamp. use case e.g. setting bar
value below zero
fixes #1188
=> feat(scales): add option to clamp linear scales

packages/axes/src/compute.js
This will fix RTL issue with the x-axis label. When using `tickRotate`, `text-align` is incorrect. Most RTL issues are solvable using a small trick like this one.
=> fix(axes): rtl issue with x-axis

packages/axes/src/components/Axis.js, packages/axes/src/compute.js
Fix for https://github.com/plouc/nivo/issues/1379
The transition uses an ever-incrementing key when the type of the provided key is a `Date`.
=> fix(axis): time series rendering

packages/voronoi/index.d.ts
=> fix(voronoi): fix typo in export class name

packages/voronoi/stories/voronoi.stories.js
This will fix unique key issues & length of undefined for `voronoi`. 
Dev (Warning only shows in dev. The `undefined` error happens after a few seconds.): 
Prod (The `undefined` error happens after a few seconds.): 
Fix:
---
❤️ this project. i contributed in [opencollective.com/nivo](https://opencollective.com/nivo).
=>  fix(voronoi): length undefined in production

packages/scales/index.d.ts, packages/scales/package.json, packages/scales/src/linearScale.js, packages/scales/src/timeScale.js, packages/scales/tests/linearScale.test.js
This exposes being able to run the builtin d3 `nice` function over the linear and time scales, which smoothes out the starting/ending points of the range. In both cases, they accept either no argument, a numeric `tickCount`, and in the case of the time scale, a time interval.
=> feat(scales): add nice argument to linear and time scales

packages/bar/src/compute/common.js, packages/bar/src/compute/grouped.js
Bar charts are very slow to render with large data sets. It is clearly noticeable on the website example as well: https://nivo.rocks/bar/canvas/
These 2 changes significantly improve the performance:
- don't create new objects in every iteration of `reduce` in `filterNullValues` and `normalizeData` (even though the syntax is less elegant it is far more performant). See [this](https://www.richsnapp.com/article/2019/06-09-reduce-spread-anti-pattern) blog for more explanation.
- only calculate the cleaned data once as it doesn't depend on the keys
=> fix(bar): improve grouped bar performance

Makefile
This allows to run `lint --fix` on the files so lint fixes everything it can e.g. formating changes
=> [feature/lint-fix] add lint --fix option and create new make option

packages/core/index.d.ts
Markers are missing two props in their type declarations, `legendOrientation` and `legendPosition`. Those props can be seen in use at [nivo.rocks/adding-markers](https://nivo.rocks/storybook/?path=/story/line--adding-markers).
`legendPosition` utilizes the type declared at [line 20](https://github.com/plouc/nivo/blob/3ba34a22aed3c85f09976f6afee0b42805a04a40/packages/core/index.d.ts#L20) - `BoxAlign`, while `legendOrientation` has a hard coded union `'horizontal' | 'vertical'`.
Additionally, [line 168](https://github.com/plouc/nivo/blob/3ba34a22aed3c85f09976f6afee0b42805a04a40/packages/core/index.d.ts#L168) reuses an already declared `DatumValue` type from [line 5](https://github.com/plouc/nivo/blob/3ba34a22aed3c85f09976f6afee0b42805a04a40/packages/core/index.d.ts#L5).
<hr />
Thanks for …
=> fix(core): add missing marker typings

packages/bar/index.d.ts
Hi Raphaël Benitte,
Thanks for creating such a wonderful chart component library.
I would like to update typedef of GraphicsContainer and on Event.
Due to Nivo provide custom `barComponent` props. The props of bar Item `BarItemProps` would be better to not restricted only on SVGRectElement.
=> fix(bar): types don't allow bar component as any svg element

packages/tooltip/src/context.ts
Using the tooltip hook `showTooltipFromEvent` it only allows two parameters, but in the function definition it actually receives the anchor. So, in order to the TS compilation works I had to do the following:
```
showTooltipFromEvent(
content,
event,
// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore
'left',
);
``` 
So, I added the anchor param to the `TooltipActionsContextData`, which now is:
`showTooltipFromEvent: (content: JSX.Element, event: MouseEvent, anchor?: TooltipAnchor) => void`
=> fix(tooltip): Add anchor param to showTooltipFromEvent type

packages/core/index.d.ts, packages/core/src/theming/defaultTheme.js, packages/line/src/SliceTooltip.js
I noticed that the line chart slice tooltip did not apply the theme value for chip so I created this quick fix. For that I reused the Chip component from the tooltip package.
Additionally I added another theme value to theme the value part of the tooltip.
Small preview:
=> feat(line): use theme values for line slice tooltip

packages/legends/index.d.ts
Add missing property `symbolBorderWidth` to the nivo legends Typescript typings.
=> fix(legends): Add missing symbolBorderWidth to typings

packages/line/index.d.ts
=> fix(line): update type for custom line canvas layers

packages/axes/src/components/Axes.tsx, packages/axes/src/components/Axis.tsx, packages/axes/src/types.ts
=> fix(axes): fix AxisProps types to be correct

packages/bar/src/compute/legends.js
allow for custom labels to show in the legend instead of the id or index of the series
=> feat(bar): use custom label for legends

packages/core/src/hooks/useMeasure.js
This error is hard to reproduce, but it's a straightforward workaround to make sure the observer doesn't try to update when it can't within the given frame.
Some more context about the [error](https://github.com/WICG/resize-observer/issues/38), and reference for the [workaround](https://github.com/airbnb/visx/pull/335).
=> fix(core): avoid occasional "ResizeObserver loop" error

packages/colors/package.json, packages/marimekko/package.json
Looks like these packages were outdated and weren't allowing latest version of react in the peer dependencies.
Close #1531
=> fix(colors/marimekko): update react peer dep to be < 18.0.0

packages/bump/src/bump/compute.js, packages/bump/stories/bump.stories.js
If a bump chart has more series than ranks, you run into y-scale issues as described in [this closed issue](https://github.com/plouc/nivo/issues/1337). This PR fixes that by scaling the y-axis on the number of rank values, rather than the number of series.
=> feat(bump): support more series than ranks

packages/bar/src/props.js, packages/calendar/src/props.js, packages/chord/src/props.js, packages/geo/src/props.js, packages/heatmap/src/props.js, packages/line/src/props.js, packages/network/src/props.js, packages/parallel-coordinates/src/ParallelCoordinatesCanvas.js, packages/scatterplot/src/props.js, packages/swarmplot/src/props.js, packages/treemap/src/props.js, packages/waffle/src/props.js
This change removes the use of the `global` global variable, which
doesn't exist in browsers and is automatically polyfilled by Webpack.
Other bundlers such as Vite do not do that.
Check for the presence of `window` instead, which should work in more
environments.
=> fix(packages): remove `global` from default props

packages/calendar/index.d.ts, packages/calendar/src/ResponsiveTimeRange.js, packages/calendar/src/TimeRange.js, packages/calendar/src/TimeRangeDay.js, packages/calendar/src/compute-timeRange.ts, packages/calendar/src/index.js, packages/calendar/stories/generateDayCounts.ts, packages/calendar/stories/timeRange.stories.js, packages/calendar/tsconfig.json
Re-write of  #1481,  adding new logic instead of changing the old one.  
Forked calendar preview package:
```
"@cloudbees/nivo-calendar": "0.69.4",
```
=> feat(calendar): add TimeRange component and storybook

packages/legends/src/props.ts
Close #1567
Since we are actively removing PropTypes, I think this is an acceptable compromise. Most current legends don't support passing a custom `data` property to the legends config anyways.
=> fix(legends): update proptypes to avoid generated type error

packages/core/src/hooks/useMeasure.js
Reverts "fix(core): avoid occasional "ResizeObserver loop" error (#1466)"
This reverts commit 7f88e10da2b1eae178474c9f98e6d652d4a13f6e.
Close #1561 
I'm not sure we had a report about the ResizeObserver loop, but now that the linked issue was created the reverted code is the offender. If you try the latest released version of nivo you can easily reproduce the jumpy tooltip. 
@ollwenjones Sorry I had to revert your PR, but if you want to try another attempt at fixing the ResizeObserver loop error you were receiving. I'll be more than happy to review it and ensure our tooltip doesn't regress this time.
=> chore(core): revert ResizeObserver changes

packages/pie/src/Pie.tsx, packages/pie/src/PieLegends.tsx, packages/pie/src/hooks.ts, packages/pie/src/types.ts, packages/pie/stories/pie.stories.tsx, packages/pie/tests/Pie.test.tsx
=> feat(pie): add ability to toggle serie via legend item

packages/bar/src/Bar.tsx, packages/bar/src/BarCanvas.tsx, packages/bar/src/BarItem.tsx, packages/bar/src/types.ts
=> fix(bar): fix animations when swapping keys

packages/annotations/package.json, packages/arcs/package.json, packages/axes/package.json, packages/bar/package.json, packages/bullet/package.json, packages/bump/package.json, packages/calendar/package.json, packages/chord/package.json, packages/circle-packing/package.json, packages/colors/package.json, packages/core/package.json, packages/funnel/package.json, packages/geo/package.json, packages/heatmap/package.json, packages/legends/package.json, packages/line/package.json, packages/marimekko/package.json, packages/network/package.json, packages/parallel-coordinates/package.json, packages/pie/package.json, packages/radar/package.json, packages/recompose/package.json, packages/sankey/package.json, packages/scatterplot/package.json, packages/stream/package.json, packages/sunburst/package.json, packages/swarmplot/package.json, packages/treemap/package.json, packages/voronoi/package.json, packages/waffle/package.json
BREAKING CHANGE: We upgraded react to latest version and using the new transform.
Close #1674
=> chore(deps): upgrade react minimum peer deps range to v16.14.0

packages/scales/src/timeHelpers.ts, packages/scales/src/timeScale.ts, packages/scales/tests/compute.test.ts
=> fix(scales): handle empty series with timescale

packages/bar/src/Bar.tsx
Regression was introduced with #1656. We need to specify `update` phase for our transitions.
=> fix(bar): fix animation regression

website/src/pages/faq.js
Proposing some grammatical corrections in Faq.js
=> Grammar corrections

packages/calendar/src/TimeRange.tsx, packages/calendar/src/TimeRangeDay.tsx, packages/calendar/src/compute/timeRange.ts, packages/calendar/src/types.ts, packages/calendar/stories/timeRange.stories.tsx, website/src/data/components/time-range/props.js, website/src/pages/time-range/index.js
Updated the `<TimeRange/>` component to support custom date ranges irregardless of the data provided via optional `from` and `to` props. Also added support for gaps in the data and an `emptyColor` prop for those gaps.
=> feat(timerange): add from, to, and emptyColor props

packages/scales/src/compute.ts, packages/scales/tests/compute.test.ts
The yScale.auto option is not properly computed when the data have holes and is positive. 
This PR filters those hole from the values of the chart so tat the min is not always 0 in that case.
Before:
After:
Reported also by: https://github.com/plouc/nivo/issues/859
=> Fix autoscale of linechart when data have holes.

packages/radar/src/RadarGrid.js
It seems that Radar's Axis is not currently being drawn by referring to the theme incorrectly.
Modify to draw axis using `theme.axis.domain.line`.
=> Modifying Radar's Axis to be drawn by Axis.domain.line of the Theme

packages/radar/src/Radar.tsx, packages/radar/src/RadarLayer.tsx, packages/radar/src/hooks.ts, packages/radar/src/props.ts, packages/radar/src/types.ts, packages/radar/stories/radar.stories.tsx, website/src/data/components/radar/meta.yml, website/src/data/components/radar/props.ts
Hi, we currently use this chart but need to support patterns with it. 
This PR adds defs and fill props to radar chart to support patterns and gradients.
=> feat(radar): add support for patterns and gradients

packages/core/index.d.ts, packages/core/src/components/defs/gradients/LinearGradient.js, packages/core/tests/lib/defs.test.js, packages/treemap/stories/treemap.stories.js, website/src/components/guides/gradients/GradientsExample.js
Fixes #1098
This PR allows defining gradient transforms as part of the `defs` for linear gradients. 
This fixes the (now stale, but still relevant) associated feature request #1098. 
Example usage: 
```tsx
<Line
{...commonProperties}
enableArea={true}
yScale={{
type: 'linear',
stacked: true,
}}
curve={select('curve', curveOptions, 'linear')}
defs={[
linearGradientDef(
'gradientA',
[
{ offset: 0, color: 'inherit' },
{ offset: 100, color: 'inherit', opacity: 0 },
],
{ gradientTransform: 'rotate(90 0.5 0.5)' }
),
]}
fill={[{ match: '*', id: 'gradientA' }]}
/>
```
The transform attribute follows the SVG spec documented here: https://developer.mozilla.org/en-US/docs/Web/SVG/Attribute/transform 
I added a test and modified the gradient example to show how to use that new property, which for …
=> feat(defs): allow gradientTransform to be passed to gradient definitions

packages/radial-bar/src/RadialBar.tsx
Sorry for the tiny pull request, but I stumbled into this log in a package source, which is probably an unwanted development artifact.
=> fix(radial-bar): remove unnecessary console log

packages/annotations/package.json, packages/arcs/package.json, packages/axes/package.json, packages/bar/package.json, packages/bullet/package.json, packages/bump/package.json, packages/circle-packing/package.json, packages/core/package.json, packages/funnel/package.json, packages/heatmap/package.json, packages/line/package.json, packages/marimekko/package.json, packages/parallel-coordinates/package.json, packages/polar-axes/package.json, packages/radar/package.json, packages/radial-bar/package.json, packages/sankey/package.json, packages/scatterplot/package.json, packages/stream/package.json, packages/swarmplot/package.json, packages/tooltip/package.json, packages/treemap/package.json, yarn.lock
In `@react-spring/web` 9.2.6, a bug occurs on the `postinstall` script and the build fails due to weird characters. This means that `yarn install` fails for yarn 3.
9.3.1 fixes this: https://github.com/pmndrs/react-spring/releases/tag/v9.3.1
Since that version is pinned in `nivo`, no `nivo` packages could be installed using yarn 3. This simple change fixes that.
=> chore: update @react-spring/web to 9.3.1

packages/swarmplot/src/SwarmPlot.tsx, packages/swarmplot/tests/Swarmplot.test.tsx
This PR fixes #1813 by passing down the borderWidth property which was omitted in the Swarmplot component.
The result can be seen in the story at `/story/swarmplot--extra-layers` which defined a borderWidth which was not being used. It is now displaying as intended:
=> fix(swarmplot): use the borderWidth property - fixes #1813

packages/bar/src/BarCanvas.tsx, packages/bar/src/ResponsiveBarCanvas.tsx
Avoid to redefine react type ;)
The previous definition was problematic when using proptypes in a typescript file: 
Any typescript codebase importing `@nivo/bar` suddendly can't attach `propTypes` to the returned value of `forwardRef` because they are now just a function and not a `ForwardRefExoticComponent` anymore... unexpected & very disturbing.
This resulted in breaking build with typescript errors!
The symptomatic error is ts(2339):
> Property 'propTypes' does not exist on type '(props: ...) => ReactElement<...> | null'.
=> fix(bar): avoid to redefine react forwardRef type

packages/funnel/src/Funnel.tsx, packages/funnel/src/PartTooltip.tsx, packages/funnel/src/hooks.ts, packages/funnel/src/types.ts, packages/funnel/stories/funnel.stories.tsx
Adds support for 'tooltip' prop to pass a custom tooltip to Funnel, and a story to demonstrate it. Addresses #1169
=> Add support for custom tooltips in Funnel #1169

packages/core/src/components/dots/DotsItem.js
Currently this is causing error when `labelYOffset` is not provided. But since `labelYOffset` has a default value of `-12`, we should remove `required`.
=> fix: remove required for labelYOffset in DotsItem

packages/axes/src/compute.ts, packages/axes/tests/__snapshots__/compute.test.tsx.snap, packages/line/stories/line.stories.js
When using the Line-Chart as a timeline with Date-Objects on the X-Axis, the AxisTicks and GridLines are using a string representation of the x-Values' Date-Object as the react element's "key". This causes duplicate keys when the timelines scale is below 1 second intervals (since a date-objects string representation does only include seconds, for example: "Thu Sep 16 2021 09:40:59 GMT+0100 (Western European Summer Time)").
This is a small PR to use the timestamp (.valueOf()) as the react element's key for AxisTicks and GridLines, so that the Line Chart works correctly with milliseconds precision.
=> Fix: Avoid duplicate key error with time scales at millisecond precision

packages/express/src/index.ts
Fix: set `Content-Type` response header as `text/plain` rather than default `text/html`
The actual vulnerability was reported by me on huntr.dev platform.
People having write permissions on this repo can see the actual vulnerability report at:
https://huntr.dev/bounties/986fb54a-9353-43c1-9433-9a54b3d31e6e/
JamieSlome asked you to create SECURITY.md, a month ago. (https://github.com/plouc/nivo/issues/1891) for this vulnerability.
=> Fixed XSS security bug

Makefile
The makefile has a rule for linting an individual package, e.g. `make package-lint-calendar`.
The current rule does not find the intended files in the package, and prints an error.
```
No files matching the pattern "./packages/calendar/{src,tests}" were found.
Please check for typing mistakes in the pattern.
```
The pull request adjusts the rule to lint all files in `src` and `tests` directories.
=> fix makefile rule for linting an individual package

packages/line/src/Points.js
Hello 👋 
this is a fix for basically a very similar problem to #1644. If `enablePoints` is set to `true` the order of the points in any custom layer changes between the first and any subsequent render, because the points array is modified in place.
Best,
Ben
=> fix(line): make copy of points data before reversing

packages/network/src/NetworkCanvas.tsx, packages/network/src/ResponsiveNetworkCanvas.tsx, packages/network/stories/networkCanvas.stories.tsx, packages/scatterplot/src/ResponsiveScatterPlotCanvas.tsx, packages/scatterplot/src/ScatterPlotCanvas.tsx, packages/scatterplot/stories/ScatterPlotCanvas.stories.tsx
This mimics the work done in `BarCanvas.tsx` and `ResponsiveBarCanvas.tsx` to allow for custom refs for things like adding a download button.
=> Add custom ref to ScatterPlotCanvas and NetworkCanvas

packages/bar/src/types.ts
Types do not currently allow `axisBottom`, `axisLeft`, `axisRight`, or `axisTop` to be set to `null`, however this is required to disable axis and is found in the nivo documentation.
=> Allow BarCanvas axis to be nullable

examples/codesandbox/src/charts/Chord.tsx
The CodeSandbox environment spun up by #1957 failed to start, at least partially due to this typo. Revising the the typo allows the PR sandbox to initialize properly.
Sandbox created from CI for #1957:
Sandbox created from this PR:
=> codesandbox examples: fix typo in jsx prop assignment

packages/annotations/package.json, packages/arcs/package.json, packages/axes/package.json, packages/bar/package.json, packages/bullet/package.json, packages/bump/package.json, packages/chord/package.json, packages/circle-packing/package.json, packages/core/package.json, packages/funnel/package.json, packages/heatmap/package.json, packages/line/package.json, packages/marimekko/package.json, packages/network/package.json, packages/parallel-coordinates/package.json, packages/polar-axes/package.json, packages/radar/package.json, packages/radial-bar/package.json, packages/sankey/package.json, packages/scatterplot/package.json, packages/stream/package.json, packages/swarmplot/package.json, packages/tooltip/package.json, packages/treemap/package.json, yarn.lock
This is a step towards upgrading nivo to support React 18 (#1964), since this is the first version of react-spring that supports React 18.
There's no breaking changes in react-spring.
=> Upgrade react-spring to 9.4.5

packages/line/src/Points.js, packages/radar/src/Radar.tsx, packages/radar/src/RadarDots.tsx, packages/radar/src/RadarGrid.tsx, packages/radar/src/RadarGridLevels.tsx, packages/radar/src/RadarLayer.tsx, packages/radar/src/RadarSlices.tsx, packages/radar/src/hooks.ts, packages/radar/src/props.ts, packages/radar/src/types.ts, packages/radar/stories/radar.stories.tsx, packages/radar/tests/Radar.test.tsx
Addresses #1898
Provides a prop `angle` that sets the global orientation for the radar chart.
Example of a default radar chart (left, `angle=0`) and a rotated chart (right, `angle=36`):
=> feat(radar): orientation of radar chart

packages/colors/src/scales/divergingColorScale.ts, packages/colors/src/scales/sequentialColorScale.ts, packages/colors/tests/continuousColorScale.test.ts, packages/heatmap/package.json, packages/heatmap/stories/CustomInterpolator.tsx, packages/heatmap/stories/heatmap.stories.tsx, packages/heatmap/tests/HeatMap.test.tsx
Adds support for color scales with custom colors and custom interpolators
Addresses #1988
Color scales, e.g. for HeatMaps, are defined via 'sequential', 'diverging', and 'quantize' configuration types. While 'quantize' color scales can now be created with an array of custom colors, the 'sequential' and 'diverging' scales can only be selected from a set of named schemes, e.g. 'blues'. 
Custom 'sequential' and 'diverging' color scales would enable charts, e.g. HeatMaps, to integrate with the color scheme outside of the chart.
A heatmap with a sequential scheme with two custom colors:
Examples of scales with diverging colors, diverging colors with an offset, and a multi-color scheme:
(These are just for demonstration, not for use in practice.)
The new ways to define color scales are:
```
{ …
```
=> feat(colors): support sequential and diverging colors schemes with custom colors

packages/bar/src/Bar.tsx, packages/bar/src/BarCanvas.tsx, packages/bar/src/types.ts, packages/marimekko/package.json, packages/marimekko/src/Marimekko.tsx, packages/marimekko/src/hooks.ts, packages/marimekko/src/types.ts, packages/marimekko/tests/.eslintrc.yml, packages/marimekko/tests/Marimekko.test.tsx, packages/scales/src/logScale.ts, packages/scatterplot/src/ScatterPlot.tsx, packages/scatterplot/src/ScatterPlotCanvas.tsx, packages/scatterplot/src/types.ts, packages/stream/package.json, packages/stream/src/Stream.tsx, packages/stream/src/hooks.ts, packages/stream/src/types.ts
Fixes a typescript-related bug in a function that creates log scales (package `@nivo/scales`)
**Edited:** adjusts usage of scale-related ts types in packages @nivo/bar, @nivo/marimekko, @nivo/scatterplot, @nivo/stream 
The function `createLogScale` creates an object correctly. However, the way the object is returned at the end creates confusion for the TypeScript compiler, making it believe the object has an incorrect type. 
As an example, consider:
```
// prep
const mySpec: ScaleLogSpec = { type: 'log', min: 1, max: 1000 }
const myData = { all: [1, 1000], min: 1, max: 1000 }
// create scale objects
const myScale1: Scale<number, number> = createLogScale(mySpec, myData, 500, 'x') // gives error
const myScale2: Scale<any, any> = computeScale(mySpec, myData, 500, 'x')         // gives error …
```
=> fix bug (typescript) in creating log scales

packages/sankey/src/SankeyLinks.tsx, packages/sankey/src/SankeyLinksItem.tsx
Code to support custom color gradients for multiple links between the same two nodes.
Also prevents the duplicate child key error when 2+ links attach to the same two nodes.
<details><summary>(Screenshots) ResponsiveSankey: Link Color-Gradient Issue</summary>
</details>
<details><summary><b><i>Code to Generate Bug</i></b></summary>
<p>
```javascript
import { ResponsiveSankey } from '@nivo/sankey';
import { BasicTooltip } from '@nivo/tooltip';
<ResponsiveSankey enableLinkGradient
colors={(node) => node.nodeColor}
linkTooltip={({ link }) => {
const value = `(${link.linkLabel}) ${link.source.nodeLabel} > ${link.target.nodeLabel}: ${link.value}`;
return <BasicTooltip enableChip color={link.endColor} value={value} />; 
}}
data={{
nodes: [
{ id: "node1", nodeColor: "#e0e0e0", nodeLabel: "Node …
```
=> Include link's index in the React Component key when creating the SVG element

packages/core/src/lib/interactivity/index.js, packages/tooltip/src/hooks.ts
In a normal situation mouse enter / mouse leave events capture the position ok. But when the chart is inside a scaled
element with a CSS transform like: `transform: scale(2);` tooltip are not positioned ok. Comparing original width `box.width` agains scaled width give us the scaling factor to calculate ok mouse position.
This PR [fix this issue](https://github.com/plouc/nivo/issues/2033)
The problem as explained in the issue that when the charts are inside an scaled div like this:
```javascript
<div style={{ transform: 'scale(2)' }}>
<MyFancyNivoChart />
</div>
```
The tooltip will be misplaced as you can see in the video in the issue I linked
I found [the solution here](https://github.com/mapbox/mapbox-gl-js/pull/10096)
=> Fix tooltip positioning when charts are rendered inside an scaled div

packages/geo/src/Choropleth.js, packages/geo/src/GeoMapFeature.js, packages/geo/src/props.js, website/src/pages/choropleth/index.tsx
Event if it's in the [documentation](https://nivo.rocks/choropleth/), the usage of `defs` and `fill` was missing its implementation in the Choropleth Map component.
This PR adds this features, addressing issues #2068 (and the old #864) and, with a little workaround, also the first question of #2064 (it's enough to define a gradient with the same starting and ending color to achieve what was asked).
As was done in other components, now the Choropleth component read the `defs` and `fill`, uses the `bindDefs` method to bind them to the data, and pass them to the `SvgWrapper` component.
Then, each map `features` check is there's a `fill` property defined. If so it uses as fill color, otherwise it uses the calculated color.
This PR also adds three example patterns to the Nivo Website: …
=> feat(choropleth): add defs and fill capabilities

packages/bar/package.json
I've been facing hoisting issues while using nivo on a monorepo app with Lerna / Yarn workspaces, leading to runtime errors due to an incorrect React context, probably because the `@nivo/core` module was duplicated at the root of the app and inside each project.
Wondering if that could be because `@nivo/bar` is not using the same minor version for `d3-shape` as other packages.
=> Align d3-shape version on bar with other packages

packages/core/src/lib/interactivity/index.js
Fix for https://github.com/plouc/nivo/issues/2122.
=> fix(canvas): fix getRelativeCursor for non SVG implementations

packages/core/src/hooks/useMeasure.js
**ResizeObserver** is not implemented in all environments, for example, [jsdom](https://github.com/jsdom/jsdom/issues/3368).
This forces nivo library consumers to mock or add polyfils, for example [jest.setup.js](https://github.com/plouc/nivo/blob/1867b606111ad1253cadb7e3cbcab2663c3275c5/packages/jest.setup.js).
Checking for global ResizeObserver removes the need to have it on the global window object.
=> Check if ResizeObserver is defined instead of checking window object

packages/line/index.d.ts
=> bugfix: fix CustomLayerProps lineGenerator type by removing unnecessary Array type

packages/line/src/Line.js, packages/line/src/Slices.js, packages/line/src/SlicesItem.js, packages/line/tests/Line.test.js
On the Line chart the mouse events (`onMouseEnter`, `onMouseMove`, `onMouseLeave` and `onClick`) work fine when the mesh is enabled but not when the slices are enabled. This PR fixes that.
Related issue: #1401.
=> Add mouse events to line slices

packages/annotations/package.json, packages/arcs/package.json, packages/axes/package.json, packages/bar/package.json, packages/bullet/package.json, packages/bump/package.json, packages/chord/package.json, packages/circle-packing/package.json, packages/core/package.json, packages/funnel/package.json, packages/heatmap/package.json, packages/line/package.json, packages/marimekko/package.json, packages/network/package.json, packages/parallel-coordinates/package.json, packages/polar-axes/package.json, packages/radar/package.json, packages/radial-bar/package.json, packages/sankey/package.json, packages/scatterplot/package.json, packages/stream/package.json, packages/swarmplot/package.json, packages/tooltip/package.json, packages/treemap/package.json, yarn.lock
Having a constraint on `@react-spring/web` blocking it to a very precise version (here: `9.4.5`) can push users of nivo into pulling it several times in their node_modules or bundles if they don't really check for duplicated packages. Indeed it's rather simple to have two distinct libraries requesting it at version `9.x` at the same time, and if one of them (not nivo) request something not being `9.4.5` they we would pull the library twice.
It seems that given `@react-spring/web` seems to follow semver, there is not real risk to say nivo supports `^9.4.5` instead of `9.4.5` only.
=> fix: Relax constraints on `@react-spring/web`

packages/calendar/src/TimeRange.tsx, packages/calendar/src/compute/timeRange.ts, packages/calendar/src/props.ts, packages/calendar/src/types.ts, website/src/data/components/time-range/props.ts, website/src/pages/time-range/index.js
So that Monday could be first.
=> Add firstWeekday attr to calendar/TimeRange

packages/pie/tests/Pie.test.tsx
While reviewing the Pie Chart code, I noticed that unit tests for the gradients attribute were missing
=> Add tests for gradients attribute

website/src/components/components/explorer/ComponentsExplorer.tsx, website/src/pages/components.tsx
Resolves https://github.com/plouc/nivo/issues/2346
Found that the `navigate` function being passed from `Components` to `ComponentsExplorer` was `undefined`. Importing `navigate` from `gatsby` in the `ComponentsExplorer` instead.
=> Fix website component search

tsconfig.monorepo.json
When upgrading my app from `0.73.0` to `0.83.0`, I received the following error message:
```
Could not find a declaration file for module '@nivo/waffle'. '.../node_modules/@nivo/waffle/dist/nivo-waffle.cjs.js' implicitly has an 'any' type.
Try `npm i --save-dev @types/nivo__waffle` if it exists or add a new declaration (.d.ts) file containing `declare module '@nivo/waffle';`
```
I used the same approach as #2351 and verified that the types are now generated when running `make init`.
=> fix: waffle types missing from dist

packages/arcs/src/arc_link_labels/useArcLinkLabelsTransition.ts, packages/pie/src/Pie.tsx, packages/pie/src/props.ts
Noticed the `arcLinkLabelsOffset` control wasn't doing anything on the [pie chart demo](https://nivo.rocks/pie/).
Tracked it down to a couple of issues:
1. In the default props, the `arcLinkLabels` layer came before the `arcs` layer so arcs were being rendered over the top of the arc link labels.
2. The `offset` was not being included in the dependency array for `useTransitionPhases` so changing the `arcLinkLabelsOffset` required another prop to change before the offset would update in the UI.
=> Fix arcLinkLabelsOffset for pie chart

packages/stream/src/hooks.ts
The stream diagram was overflowing. Particularly in the "silhouette" mode. This was introduced in d53681b439d3bac08e978491a56518b3fe9c98b5 where the d3 scale was replaced with the nivo equivalent. While ignoring that the min value might be negative thus must be put into the first parameter.
This closes: #2391
=> fix(stream): fix stream diagram overflowing

packages/calendar/src/compute/timeRange.ts
This is a proposed fix for https://github.com/plouc/nivo/issues/2419
The function `shiftArray` mutates `ARRAY_OF_WEEKDAYS` which results in a wrong week day display in certain situations.
=> shiftArray in calendar/src/compute/timeRange.ts should not mutate its argument

packages/pie/src/Pie.tsx, packages/pie/src/PieCanvas.tsx, packages/pie/src/PieLegends.tsx, packages/pie/src/hooks.ts, packages/pie/src/types.ts, packages/pie/tests/Pie.test.tsx, packages/waffle/src/hooks.ts, storybook/stories/pie/Pie.stories.tsx, storybook/stories/pie/PieCanvas.stories.tsx, storybook/stories/waffle/Waffle.stories.tsx, website/src/data/components/pie/meta.yml, website/src/data/components/pie/props.ts
Please see https://github.com/plouc/nivo/issues/2388 and https://github.com/plouc/nivo/issues/2406 for context.
=> Pie: Add the ability to programmatically control the activeId

packages/core/src/components/cartesian/markers/CartesianMarkersItem.js, packages/core/src/components/defs/patterns/PatternDots.js, packages/core/src/components/defs/patterns/PatternLines.js, packages/core/src/components/defs/patterns/PatternSquares.js, packages/core/src/motion/context.js, packages/funnel/src/props.tsx, packages/geo/src/Choropleth.js, packages/geo/src/ChoroplethCanvas.js, packages/geo/src/GeoMap.js, packages/geo/src/GeoMapCanvas.js, packages/line/src/Line.js, packages/line/src/LineCanvas.js, website/src/components/guides/patterns/PatternsDotsDemo.tsx, website/src/components/guides/patterns/PatternsLinesDemo.tsx, website/src/components/guides/patterns/PatternsSquaresDemo.tsx
Refactor default props declared like:
```
Component.defaultProps = {
prop1: 0,
prop2: 1,
// ....
}
```
Now, the default props are defined directly inside the component
```
export const Component = props => {
const {
prop1 = 0,
prop2 = 1,
// ...
} = props
// ...
}
```
The given solution is based in the issue from another repository:
- chakra-ui/chakra-ui#7057
=> refactor default props to fix error message

packages/sankey/src/types.ts
This PR is aimed to address a typing issue when custom types for Node and Link are not passed into the onClick handler of sankey chart and replaced with the `DefaultNode` and `DefaultLink` instead
=> fix(sankey): update onClick types in sankey chart to respect generics

website/src/components/guides/theming/defaults.ts
This PR will the error appearing on the website when trying to expand tooltip.container in "/guides/theming/"
It should solve the issue #2520
=> fix tooltip default color

package.json, packages/core/package.json, packages/tooltip/package.json, pnpm-lock.yaml
* Declare `prop-types` as a dependency of `@nivo/core` (as recommended in their README)
* Declare `react` as a peer dependency of `@nivo/tooltip`
* Declare correct version of `pnpm`
* Update lockfile
Fixes #2401
=> Fix (peer) dependencies

packages/tooltip/src/TooltipWrapper.tsx
This was fine in version [0.62.0](https://github.com/plouc/nivo/blob/v0.62.0/packages/tooltip/src/components/TooltipWrapper.js#L61) but then there was an deletion of `opacity` field [here](https://github.com/plouc/nivo/commit/f712cfaa1b75917784506989949a2483f652cd8b#diff-2f78a5f86f826d7d62620d77e404af45289179ffdade0c0f6d0f91362192afb0L75) in version [0.64.0](https://github.com/plouc/nivo/blob/v0.64.0/packages/tooltip/src/components/TooltipWrapper.js#L76) with motivation (taken from the corresponding [PR](https://github.com/plouc/nivo/pull/1185)):
> I also got rid of the opacity property since I didn't see a scenario where it should be set to 0 after this change, but let me know if I missed anything and I can add that back.
Removing the `opacity` caused the flash effect and weird initial …
=> Tooltip: avoid a flash effect and weird initial transition

packages/line/src/hooks.js, packages/line/tests/Line.test.js
Rewrite componentId to support react17
**Issue:** https://github.com/plouc/nivo/issues/2536
I fully understand the benefits of react useId hook but it doesn't work for react 17. As in new versions this lib resolved all vulnerabilities issues it will be great to support react 17 as well. I’ve just rewritten it to "lodash/uniqueId" and then it can be supported for all versions.
Thank you
=> Rewrite componentId to support react17

packages/line/src/LineCanvas.js
This PR fixes the inconsistent rendering of `enableArea` when comparing SVG to Canvas, seen below is a example of the issue. The SVG line renders the area correctly when using a stacked line graph but the current implementation of the Canvas line renders it improperly.
This fix will make the canvas version conform with how the svg version is displayed.
SVG Line Area example (Current Good ✔️):
Canvas Line Area example (Current Not Good ❌):
Canvas Line Area example (Fixed Good ✔️):
=> Fix area rendering disparity of line canvas compared to line svg

packages/line/index.d.ts, packages/line/src/Line.js, packages/line/src/Points.js, packages/line/tests/Line.test.js, website/src/data/components/line/mapper.ts
💥 Breaking change
This is a rework PR for what was proposed for #1981 .
We achieve the same goal but instead pass the whole `Point` informations to the `AccessorFunc` directly.
Compared to the first version of the PR, this one comes with :
- Updates related to the Website to not break existing examples
- Unit tests for the case with a function and the case with a string passed to the `pointLabel` prop
=> feat(Line): passing the full Point info to the `AccessorFunc` for Label

packages/bar/src/Bar.tsx, packages/bar/src/BarCanvas.tsx, packages/bar/src/types.ts
I was creating a custom layer for my bar chart and didn't find a way to access the colours passed to the chart.
Figured that the most correct approach is to actually pass `colors` and `colorBy` props to the layer so I could use `const getColor = useOrdinalColorScale(colors, colorBy)` in my custom layer.
=> Add getColor to props provided to custom layers

packages/core/src/components/Container.js, packages/core/src/components/LegacyContainer.js
Notably fixes a warning we encounter regularly using this package.
=> Allow for actual motionConfig proptypes on <Container />

packages/line/tests/Line.test.js, packages/voronoi/src/hooks.ts
This PR fixes issue described on #2597 
The issue we had was that we are calling `delaunay.find` function on empty data, it was fixed on their side but new version was not deployed yet so we still need to make a fix around this.
The simple fix I found was to early return when we have `nodes.length === 0`.
I've also added a simple test around Line Chart
=> 🐛  [#2597] Prevent Line Chart from crashing when having no data

packages/marimekko/src/hooks.ts, packages/marimekko/src/types.ts, storybook/stories/marimekko/Marimekko.stories.tsx
Currently, only the dimensionId as well as the patched value function are propagated to the computed data.
In order to use custom colors per dimension, it is necessary to propagate the entire object to the computed one so the dimension data is still available.
Resolves #2677
=> marimekko: all dimension input data is propagated

packages/sankey/src/types.ts
The component actually clones data that it mutates, and only iterate over the other arrays, so making them readonly is restricting the props types without any change.
=> fix(sankey): use readonly array types in props

packages/sankey/src/types.ts
The code was actually already handling custom layers, this change only surfaces this capacity in the types.
=> feat(sankey): enable custom layers in Sankey diagram

packages/sankey/src/Sankey.tsx, packages/sankey/src/hooks.ts, packages/sankey/src/types.ts
Hey @plouc, thanks for your work on this library! 🤗
Some time ago I have created an [Issue#2700](https://github.com/plouc/nivo/issues/2700), where described some needed "edge case" functionality. As I got it you like an idea todo it. So I have opening the PR with those changes.
- `isCurrentNode` and `isCurrentLink` methods were wrapped in `useMemo` to avoid unnecessary re-rendering, due to the recalculation of the sankey chart `meta` layer props;
- `layerProps` variable is also wrapped in `useMemo` to avoid unnecessary re-renders;
- Some `@ts-ignore`'s has been replaced by `@ts-expect-error`;
- Typing adjustments to support updated `layerProps`.
```
type SankeyLayer = 'links' | 'nodes' | 'labels' | 'legends' | React.FC<CustomSankeyLayerProps>
```
`<Sankey ... layers={['links', 'nodes', …
=> feat (sankey): provide additional 'layerProps' for the custom layers

packages/core/src/lib/interactivity/detect.js
This PR brings to the table some performance improvement for `getDistance` calculations. The performance improvement is more evident in Chrome, whereas in Safari the ops/s gains look minimal.
Here's a quick benchmark: https://jsbenchmark.com/#eyJjYXNlcyI6W3siaWQiOiJ3N25aUzVrc2hScHBzSlRoTldIMGgiLCJjb2RlIjoiREFUQS5mb3JFYWNoKCh7IHgyLCB4MSwgeTIsIHkxLCB9KSA9PiAgTWF0aC5zcXJ0KCgoeDIgLSB4MSkgKiogMikgKyAoKHkyIC0geTEpICoqIDIpKSkiLCJuYW1lIjoiSW5saW5lIiwiZGVwZW5kZW5jaWVzIjpbXX0seyJpZCI6IlpaSjZycGo0NFhSOFdHZVdraXMtdiIsImNvZGUiOiJEQVRBLmZvckVhY2goKHsgeDIsIHgxLCB5MiwgeTEsIH0pID0-IHtcbiAgICBsZXQgZGVsdGFYID0geDIgLSB4MVxuICAgIGxldCBkZWx0YVkgPSB5MiAtIHkxXG5cbiAgICBkZWx0YVggKj0gZGVsdGFYXG4gICAgZGVsdGFZICo9IGRlbHRhWVxuXG4gICAgcmV0dXJuIE1hdGguc3FydChkZWx0YVggKyBkZWx0YVkpXG59KSIsIm5hbWUiOiJMZXQiLCJkZXBlbmRlbmNpZ …
=> perf: faster getDistance calculations

packages/bar/src/BarTotals.tsx
Hey there 👋🏻,
I recently noticed that the color of the total label in stacked bar charts is being overridden by 'fill: theme.text.fill'. 
It seems more logical to use the 'theme.labels.text' props instead, since it's specifically for labels. 
What are your thoughts on this @plouc?
=> Remove fill property in BarTotals.tsx

packages/calendar/src/TimeRange.tsx, packages/calendar/src/compute/timeRange.ts, packages/calendar/src/props.ts, packages/calendar/src/types.ts, website/src/data/components/time-range/props.ts
Adds support for changing time range's weekday labels for localization or other purposes. 
Addresses https://github.com/plouc/nivo/issues/1979 and https://github.com/plouc/nivo/issues/1822
Adds new prop `weekdays: string[]` to `TimeRange` component. The `weekdays` array should contain labels for the weekdays starting from sunday.
TimeRange with Finnish labels
```JavaScript           
<ResponsiveTimeRange
data={data}
monthLegend={(_y, _m, date) => months[date.getMonth()]}
firstWeekday={"sunday"}
weekdayTicks={[0, 2, 4]}
weekdays={['Sunnuntai', 'Maanantai', 'Tiistai', 'Keskiviikko', 'Torstai', 'Perjantai', 'Lauantai']}
/>
```
=> feat(timerange): custom weekday labels for TimeRange

packages/radial-bar/src/types.ts
Added a generic to RadialBarTooltipComponent, to better enforce the datum type.
=> fix: RadialBarTooltipComponent type

packages/funnel/src/hooks.ts
This fixes what I think is a simple merge miss.
https://github.com/plouc/nivo/pull/2704 added these two imports, but https://github.com/plouc/nivo/pull/2712 did at the same time add `.js` to all lodash imports.
This causes a build error in one of my projects.
=> fix: add extension for lodash imports in funnel package

packages/geo/package.json
This solves an issue where the types for the `@nivo/geo` package was not included.
I tested it by opening `website/src/pages/choropleth/index.tsx` on master and on this branch. Where I did get an error about missing types in my editor on master, the error was not present on this branch.
To solve it, I copied the way it was done in `@nivo/line`, which seems to be one of the few places where an `index.d.ts` is used as well.
=> fix: add types to geo package

packages/scales/package.json, packages/scales/src/linearScale.ts, packages/scales/src/types.ts, packages/scales/tests/linearScale.test.ts, pnpm-lock.yaml, storybook/stories/line/Line.stories.tsx
Hi @plouc,
Thank you for the great library. This PR addresses the issue raised in https://github.com/plouc/nivo/issues/2707 - we are also observing the same behaviour in our product.
- The name of the property is the same as `ScaleBandSpec.round` for consistency.
- The property is enabled by default to avoid breaking the existing codebases.
Before:
After:
Let me know if there is anything else that needs to be updated in order for this PR to land.
---
Rounding the output values to the nearest integer causes artifacts on charts with high-frequency data. The new option allows for this behaviour to be disabled.
=> feat(scales): add `round` option to linear scale spec

cypress/src/components/line/Line.cy.tsx, packages/core/index.d.ts, packages/core/src/components/dots/DotsItem.js, packages/line/src/Line.tsx, packages/line/src/LineCanvas.tsx, packages/line/src/Points.tsx, packages/line/src/defaults.ts, packages/line/src/hooks.ts, packages/line/src/types.ts, packages/line/tests/Line.test.tsx, website/src/data/components/line/generator.ts, website/src/data/components/line/props.ts, website/src/lib/chart-properties/accessibility.ts, website/src/pages/line/index.tsx
This is a first step to try to improve this package accessibility.
Adds the following properties to the `Line` component:
- `ariaLabel`
- `ariaLabelledBy`
- `ariaDescribedBy`
- `isFocusable`
- `pointAriaLabel`
- `pointAriaLabelledBy`
- `pointAriaDescribedBy`
- `pointAriaHidden`
- `pointAriaDisabled`
We can navigate through points via the keyboard, but this doesn't work if using slices.
Also fixes https://github.com/plouc/nivo/issues/2659.
=> @nivo/line a11y improvements

packages/line/src/types.ts, packages/scales/src/compute.ts
After version 0.92, our custom line charts are missing some pieces to get their types properly.
=> feat(line): improve types for custom layers.

packages/sankey/src/Sankey.tsx, packages/sankey/src/SankeyLabels.tsx, packages/sankey/src/props.ts, packages/sankey/src/types.ts, packages/text/src/Text.tsx
Before this change it was possible not to show the layer props and build an custom layer for labels, however the internal labels layer is pretty cool and compute a lot of useful thing. Exposing the component make it customizable when one wants only to change the render of each label
=> feat(sankey): make it easy to use a different component for labels
